# Dataframes

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn

In [3]:
# mit NUmpy einen Seed festlegen
np.random.seed(101)

In [4]:
# Dataframe anlegen
# Beim Index müssen die Werte nicht separat übergeben werden ('a','b','c','d'). 
# Es genügt einfach 'a b c d' zu schreiben, muss aber mit split() wieder unterteilt werden.

df = pd.DataFrame(randn(5,4), index='A B C D E'.split(),columns='W X Y Z'.split())

In [5]:
# Dataframe ist eine Matrix mit verschiedenen Spalten und Zeilen

df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [7]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [8]:
# SQL Syntax

df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [9]:
df.W,df.Z

(A    2.706850
 B    0.651118
 C   -2.018168
 D    0.188695
 E    0.190794
 Name: W, dtype: float64,
 A    0.503826
 B    0.605965
 C   -0.589001
 D    0.955057
 E    0.683509
 Name: Z, dtype: float64)

In [10]:
# Die Spalten sind vom Datenyp Series! testen mit type()

type(df['W'])

pandas.core.series.Series

In [11]:
# Addition von den Spalten 'W' und 'Y' ergibt Spalte 'neu'

df['neu'] = df['W'] + df['Y']

In [12]:
df

          W         X         Y         Z       neu
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [13]:
# Spalten entfernen und mit axis=  definieren ob es sich um eine Spalte oder Zeile handelt (Spalte=1, Reihe=0)

df.drop('neu',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
# erneutes aufrufen zeigt, dass die gelöschte Spalte wieder da ist
df

          W         X         Y         Z       neu
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [15]:
# inplace=True entfernt die Spalte dauerhaft

df.drop('neu',axis=1,inplace=True)

In [16]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [17]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [18]:
df.drop('E',axis=0,inplace=True)

In [19]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [20]:
# Zeilen anzeigen lassen


df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [21]:
# IndexLoc: Zeilen über den Indexwert anzeigen lassen

df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [22]:
# Subset von Zeilen und Spalten (Koordinate) auswählen

df.loc['B','Y']

np.float64(-0.8480769834036315)

In [23]:
# Subset vom Dataframe

df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

# Teil 2

In [24]:
# Dataframe anlegen
# Beim Index müssen die Werte nicht separat übergeben werden ('a','b','c','d'). 
# Es genügt einfach 'a b c d' zu schreiben, muss aber mit split() wieder unterteilt werden.

df = pd.DataFrame(randn(5,4), index='A B C D E'.split(),columns='W X Y Z'.split())

In [25]:
# bedingte Auswahl:
# Boolianwerte ausgeben

df>0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [26]:
# bedingte Auswahl

df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [27]:
# Verschärfte bedingte Auswahl

df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [28]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [29]:
df[df['W']>0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [30]:
df[df['W']>0][['Y','X']]

          Y         X
A -1.706086  1.693723
C  0.638787  0.072960

In [31]:
df[df['W']>0][['Y','X','Z']]

          Y         X         Z
A -1.706086  1.693723 -1.159119
C  0.638787  0.072960  0.329646

In [32]:
# Neues Dataframe anlegen: Bedingungen müssen mit runder Klammer übergeben werden!
# Das 'and' führt hier zum Fehler ambiguous=mehrdeutig

df[(df['W']>0)and(df['Y']>1)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# anstatt das and muss & verwendet werden zum erstellen des neuen Dataframes

df[(df['W']>0)&(df['Y']>1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [ ]:
# anstatt ein or hier ein | verwenden zum erstellen des neuen Dataframes

df[(df['W']>0)|(df['Y']>1)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [ ]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
# Index auf Standarindex zurücksetzen

df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [ ]:
# Index wieder neue Werte zuweisen

neuind = 'BY BW HH BB NW'.split()

In [ ]:
df['Staaten']=neuind

In [ ]:
df

          W         X         Y         Z Staaten
A  0.302665  1.693723 -1.706086 -1.159119      BY
B -0.134841  0.390528  0.166905  0.184502      BW
C  0.807706  0.072960  0.638787  0.329646      HH
D -0.497104 -0.754070 -0.943406  0.484752      BB
E -0.116773  1.901755  0.238127  1.996652      NW

In [ ]:
# Index ändern: Aber wird nicht gespeichert! Probiere separate Ausgabe

df.set_index('Staaten')

                W         X         Y         Z
Staaten
BY       0.302665  1.693723 -1.706086 -1.159119
BW      -0.134841  0.390528  0.166905  0.184502
HH       0.807706  0.072960  0.638787  0.329646
BB      -0.497104 -0.754070 -0.943406  0.484752
NW      -0.116773  1.901755  0.238127  1.996652

In [ ]:
df

          W         X         Y         Z Staaten
A  0.302665  1.693723 -1.706086 -1.159119      BY
B -0.134841  0.390528  0.166905  0.184502      BW
C  0.807706  0.072960  0.638787  0.329646      HH
D -0.497104 -0.754070 -0.943406  0.484752      BB
E -0.116773  1.901755  0.238127  1.996652      NW

In [ ]:
# Index dauerhaft ändern mit inplace=True

df.set_index('Staaten', inplace=True)

In [ ]:
df

                W         X         Y         Z
Staaten
BY       0.302665  1.693723 -1.706086 -1.159119
BW      -0.134841  0.390528  0.166905  0.184502
HH       0.807706  0.072960  0.638787  0.329646
BB      -0.497104 -0.754070 -0.943406  0.484752
NW      -0.116773  1.901755  0.238127  1.996652

# Teil 3
- Multiindexierung

In [ ]:
aussen = ['G1','G1','G1','G2','G2','G2']
innen = [1,2,3,1,2,3]
hier_index = list(zip(aussen, innen))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2), index=hier_index,columns=['A','B'])

In [ ]:
df

             A         B
G1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
G2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

In [ ]:
df.loc['G1'].loc[1]

A    0.147027
B   -0.479448
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['Gruppe', 'Num']

In [ ]:
df

                   A         B
Gruppe Num
G1     1    0.147027 -0.479448
       2    0.558769  1.024810
       3   -0.925874  1.862864
G2     1   -1.133817  0.610478
       2    0.386030  2.084019
       3   -0.376519  0.230336

In [ ]:
df.xs('G1')

            A         B
Num
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [ ]:
df.xs(('G1',1))

A    0.147027
B   -0.479448
Name: (G1, 1), dtype: float64

In [ ]:
df.xs(1,level='Num')

               A         B
Gruppe
G1      0.147027 -0.479448
G2     -1.133817  0.610478