# DataFrame Operations

In [58]:
import pandas as pd

In [59]:
df = pd.DataFrame({'spa1':[1,2,3,4],
                   'spa2':[444,555,666,444],
                   'spa3':['abc','def','ghi','xyz']})

In [60]:
df.head()

   spa1  spa2 spa3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [61]:
df

   spa1  spa2 spa3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [62]:
# einmalige Werte filtern

df['spa2'].unique()

array([444, 555, 666])

In [63]:
# ANzahl einmaliger Werte filtern

df['spa2'].nunique()

3

In [64]:
# Die FUnktion agiert wie groupby() der spa2 und gibt die Anzahl der Werte aus

df['spa2'].value_counts()

spa2
444    2
555    1
666    1
Name: count, dtype: int64

In [65]:
# neuen DataFrame vom bestehenden erstellen mit einer Bedingung (nehme alle Werte, die in der spa1 größer 2 sind in das neue DataFrame auf)
new_df= df[(df['spa1']>2)]

In [66]:
new_df

   spa1  spa2 spa3
2     3   666  ghi
3     4   444  xyz

In [67]:
# Zweite Bedingung/Einschränkung (Nehme alle Werte aus spa2, die gleich 444 sind)

new_df= df[(df['spa1']>2)&(df['spa2']==444)]

In [68]:
new_df

   spa1  spa2 spa3
3     4   444  xyz

In [69]:
# Funktion einer einfachen Multiplikation erstellen

def mal2(x):
    return x*2

In [70]:
# Funktion mal2 auf spa2 anwenden mit .apply(mal2)

df['spa2'].apply(mal2)

0     888
1    1110
2    1332
3     888
Name: spa2, dtype: int64

In [71]:
# Länge der Strings in spa3 ausgeben mit .apply(len)

df['spa3'].apply(len)

0    3
1    3
2    3
3    3
Name: spa3, dtype: int64

In [72]:
# Lambda-Funktion anwenden und die Werte in spa2 mit 2 multiplizieren

df['spa2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: spa2, dtype: int64

In [73]:
# mal 2

df['spa2']*2

0     888
1    1110
2    1332
3     888
Name: spa2, dtype: int64

In [74]:
# Aggregationsfunktion

df['spa1'].sum()

np.int64(10)

In [75]:
df['spa1'].min()

np.int64(1)

In [76]:
df['spa1'].max()

np.int64(4)

In [77]:
df.drop('spa1',axis=1)

   spa2 spa3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [78]:
df

   spa1  spa2 spa3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
# spa1 dauerhaft löschen mit del df['spa1]

del df['spa1']

In [80]:
df

   spa2 spa3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
# Atribut Spalte ausgeben lassen

df.columns

Index(['spa2', 'spa3'], dtype='object')

In [ ]:
# Atribut Index ausgeben lassen

df.index

RangeIndex(start=0, stop=4, step=1)

# Sortieren und Ordnen

In [83]:
df

   spa2 spa3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
# DataFrame dauerhaft sortiert

df.sort_values(by='spa2')

   spa2 spa3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [85]:
df.sort_values(by='spa2', inplace=True)

In [87]:
df.isnull()

    spa2   spa3
0  False  False
3  False  False
1  False  False
2  False  False

In [88]:
# NULL-Werte entfernen

df.dropna()

   spa2 spa3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

## NULL-Werte befüllen

In [90]:
import numpy as np

In [92]:
# DataFrame mit NULL-Werten erstellen

df = pd.DataFrame({'spa1':[1,2,3,np.nan],
                   'spa2':[np.nan,555,666,444],
                   'spa3':['abc','def','ghi','xyz']})

In [94]:
df.head()

   spa1   spa2 spa3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [96]:
# NULL-Werte befüllen

df.fillna(0)

   spa1   spa2 spa3
0   1.0    0.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz

## Pivotieren

In [97]:
data = pd.DataFrame({'A':['foo','foo','foo','bar','bar','bar'],
                    'B':['one','one','two','two','one','one'],
                    'C':['x','y','x','y','x','y'],
                    'D':[1,3,2,5,4,1]})

df=pd.DataFrame(data)

In [98]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [99]:
df.pivot_table(values='D',index=['A','B'],columns='C')

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN