# Group By

In [69]:
import pandas as pd

In [70]:
# Data Frame erstelllen
data={'Firma':['GOOG','GOOG','MSFT','MSFT','FB','FB'], 'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,12,340,124,243,350]}

In [71]:
df=pd.DataFrame(data)

In [72]:
print(df)

  Firma   Person  Sales
0  GOOG      Sam    200
1  GOOG  Charlie     12
2  MSFT      Amy    340
3  MSFT  Vanessa    124
4    FB     Carl    243
5    FB    Sarah    350

In [73]:
df.groupby('Firma') # GroupBy-Object erhalten

In [74]:
df.groupby('Firma')['Sales'].mean() # Durchschnitt der Spalte Sales berechnen

Firma
FB      296.5
GOOG    106.0
MSFT    232.0
Name: Sales, dtype: float64

In [75]:
# oder Druchschnitt der Spalten mit numerischen Werten berechnen. Hier: Spalte Sales

df.groupby('Firma').mean(numeric_only=True)

       Sales
Firma
FB     296.5
GOOG   106.0
MSFT   232.0

In [76]:
# oder

df.groupby('Firma').mean('Sales')

       Sales
Firma
FB     296.5
GOOG   106.0
MSFT   232.0

In [77]:
nach_firma=df.groupby('Firma')

In [78]:
nach_firma.mean('Sales')

       Sales
Firma
FB     296.5
GOOG   106.0
MSFT   232.0

In [79]:
nach_firma.std(numeric_only=True)

            Sales
Firma
FB      75.660426
GOOG   132.936075
MSFT   152.735065

In [80]:
nach_firma.min()
# oder
#nach_firma.min(numeric_only=True)

        Person  Sales
Firma
FB        Carl    243
GOOG   Charlie     12
MSFT       Amy    124

In [81]:
nach_firma.max('Sales')
# oder
#nach_firma.ax(numeric_only=True)

       Sales
Firma
FB       350
GOOG     200
MSFT     340

In [82]:
# Um auch die Spalte Person mit anzuzeigen, muss hier mit Index gearbeitet werden. 

# Den Index der Zeilen finden, in denen der maximale Sales pro Firma steht
idx = df.groupby('Firma')['Sales'].idxmin()
# idx = df.groupby('Firma')['Sales'].idxmax()

# Mit diesen Indizes die Zeilen aus dem DataFrame auswählen
result = df.loc[idx]

# Optional: Nach Firma sortieren und Index auf Firma setzen
# result_sorted = result.set_index('Firma').sort_index()

result_sorted

        Person  Sales
Firma
FB        Carl    243
Goog   Charlie     12
MSFT   Vanessa    124

In [83]:
nach_firma.count()

       Person  Sales
Firma
FB          2      2
GOOG        2      2
MSFT        2      2

In [84]:
nach_firma.describe()

      Sales
      count   mean         std    min     25%    50%     75%    max
Firma
FB      2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG    2.0  106.0  132.936075   12.0   59.00  106.0  153.00  200.0
MSFT    2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [85]:
nach_firma.describe().transpose()

Firma                FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  106.000000  232.000000
      std     75.660426  132.936075  152.735065
      min    243.000000   12.000000  124.000000
      25%    269.750000   59.000000  178.000000
      50%    296.500000  106.000000  232.000000
      75%    323.250000  153.000000  286.000000
      max    350.000000  200.000000  340.000000

In [87]:
nach_firma.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     106.000000
       std      132.936075
       min       12.000000
       25%       59.000000
       50%      106.000000
       75%      153.000000
       max      200.000000
Name: GOOG, dtype: float64