# Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan], 'B':[5,np.nan,np.nan],'C':[1,2,3]})

In [3]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

## Eliminierungsverfahren
- Informationsverlust durch eliminieren der NaN-Werte (NaN = Not a Number)

In [6]:
print(df.dropna()) # Es werden nur noch Zeilen angegeben, die keine NULL-Werte (NaN-Werte) enthält. Problem: Der Wert 2 in Zeile 1 ist auch weg

     A    B  C
0  1.0  5.0  1

In [7]:
print(df.dropna(axis=1)) # Spaltenauswahl die keine NULL-Werte enthält

   C
0  1
1  2
2  3

In [8]:
df.dropna(thresh=2) # alle Zeilen rausfiltern, die mindestens 2 Nullwerte enthält

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [9]:
df.fillna(value='Füllwert')

          A         B  C
0       1.0       5.0  1
1       2.0  Füllwert  2
2  Füllwert  Füllwert  3

In [10]:
df.fillna(value=0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [11]:
df['A'].fillna(value=df['A'].mean()) # Durchschnittswert der Spalte A

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [12]:
df['A'].fillna(value=df['A'].sum()) # Durchschnittswert der Spalte A

0    1.0
1    2.0
2    3.0
Name: A, dtype: float64