In [1]:
import pandas as pd
import matplotlib.pyplot as plt
pd.options.display.float_format='{:.4f}'.format

In [2]:
close = pd.read_csv("close.csv", index_col = "Date", parse_dates = ["Date"])
close

                 BA    BTC-USD  EURUSD=X      GC=F     MSFT       ^DJI
Date
2014-10-01 108.4067   383.6150    1.2628 1214.6000  38.9529 16804.7109
2014-10-02 107.9719   375.0720    1.2624 1214.2000  38.8341 16801.0508
2014-10-03 109.8762   359.5120    1.2671 1192.2000  39.1142 17009.6895
2014-10-04      NaN   328.8660       NaN       NaN      NaN        NaN
2014-10-05      NaN   320.5100       NaN       NaN      NaN        NaN
...             ...        ...       ...       ...      ...        ...
2021-05-26 241.3700 39294.1992    1.2249 1901.3000 242.8827 34323.0508
2021-05-27 250.7000 38436.9688    1.2193 1895.7000 240.7773 34464.6406
2021-05-28 247.0200 35697.6055    1.2193 1902.5000 241.1346 34529.4492
2021-05-29      NaN 34616.0664       NaN       NaN      NaN        NaN
2021-05-30      NaN 35678.1289       NaN       NaN      NaN        NaN

[2434 rows x 6 columns]

In [3]:
# In der Datei close.csv, in der Spalte BA die NaN-Werte eliminieren (dropna()) 
# und anschließend in ein DataFrame umwandeln (to_frame()) und zuletzt eine Kopie erstellen
# diese Kopie noch eienr Variable zuweisen

msft = close.MSFT.dropna().to_frame().copy() 
msft

               MSFT
Date
2014-10-01  38.9529
2014-10-02  38.8341
2014-10-03  39.1142
2014-10-06  39.1142
2014-10-07  38.6389
...             ...
2021-05-24 242.1970
2021-05-25 243.1048
2021-05-26 242.8827
2021-05-27 240.7773
2021-05-28 241.1346

[1677 rows x 1 columns]

In [4]:
msft.dtypes

MSFT    float64
dtype: object

In [5]:
# Spalte dauerhaft neu benennen, rename colum permanently in price

msft.rename(columns={'MSFT':'Price'},inplace=True) 
msft

              Price
Date
2014-10-01  38.9529
2014-10-02  38.8341
2014-10-03  39.1142
2014-10-06  39.1142
2014-10-07  38.6389
...             ...
2021-05-24 242.1970
2021-05-25 243.1048
2021-05-26 242.8827
2021-05-27 240.7773
2021-05-28 241.1346

[1677 rows x 1 columns]

In [6]:
# verschiebt alle Werte um 1 nach unten und hinterlässt in der ersten Zeile
# ein NaN aber speichert die Änderung nicht inplace. Dazu müsste die Änderung mit = einer
# Variablen zugewiesen werden.
msft.shift(periods=1)

              Price
Date
2014-10-01      NaN
2014-10-02  38.9529
2014-10-03  38.8341
2014-10-06  39.1142
2014-10-07  39.1142
...             ...
2021-05-24 236.7790
2021-05-25 242.1970
2021-05-26 243.1048
2021-05-27 242.8827
2021-05-28 240.7773

[1677 rows x 1 columns]

In [7]:
# Mit msft['P-lag1'] wird eine eingefügt, der gleichzeitig die Kopie Spalte Price,
# in der um eins verschobenen Werte nach unten zugewiesen wird. Das Ergebnis ist dauerhaft gespeichert als msft

msft["P_lag1"] = msft.shift(periods = 1)
# msft["P_lag1"] = msft["Price"].shift(periods=1) # Gleicehr Effekt

msft

              Price   P_lag1
Date
2014-10-01  38.9529      NaN
2014-10-02  38.8341  38.9529
2014-10-03  39.1142  38.8341
2014-10-06  39.1142  39.1142
2014-10-07  38.6389  39.1142
...             ...      ...
2021-05-24 242.1970 236.7790
2021-05-25 243.1048 242.1970
2021-05-26 242.8827 243.1048
2021-05-27 240.7773 242.8827
2021-05-28 241.1346 240.7773

[1677 rows x 2 columns]

In [8]:
# ALternative 1: flexible Subtraktion

msft['P-Differenz']=msft.Price.sub(msft.P_lag1)

In [9]:
msft

              Price   P_lag1  P-Differenz
Date
2014-10-01  38.9529      NaN          NaN
2014-10-02  38.8341  38.9529      -0.1188
2014-10-03  39.1142  38.8341       0.2800
2014-10-06  39.1142  39.1142       0.0000
2014-10-07  38.6389  39.1142      -0.4752
...             ...      ...          ...
2021-05-24 242.1970 236.7790       5.4180
2021-05-25 243.1048 242.1970       0.9078
2021-05-26 242.8827 243.1048      -0.2221
2021-05-27 240.7773 242.8827      -2.1054
2021-05-28 241.1346 240.7773       0.3573

[1677 rows x 3 columns]

In [10]:
msft['P-Differenz'].head()

Date
2014-10-01       NaN
2014-10-02   -0.1188
2014-10-03    0.2800
2014-10-06    0.0000
2014-10-07   -0.4752
Name: P-Differenz, dtype: float64

In [11]:
# ALternative 2: Reihensubtraktion: Subtrahiert vorherigen Wert

msft["P_diff2"] = msft.Price.diff(periods = 1)
msft

              Price   P_lag1  P-Differenz  P_diff2
Date
2014-10-01  38.9529      NaN          NaN      NaN
2014-10-02  38.8341  38.9529      -0.1188  -0.1188
2014-10-03  39.1142  38.8341       0.2800   0.2800
2014-10-06  39.1142  39.1142       0.0000   0.0000
2014-10-07  38.6389  39.1142      -0.4752  -0.4752
...             ...      ...          ...      ...
2021-05-24 242.1970 236.7790       5.4180   5.4180
2021-05-25 243.1048 242.1970       0.9078   0.9078
2021-05-26 242.8827 243.1048      -0.2221  -0.2221
2021-05-27 240.7773 242.8827      -2.1054  -2.1054
2021-05-28 241.1346 240.7773       0.3573   0.3573

[1677 rows x 4 columns]

In [15]:
# Prüfung, ob die beiden Spalten P-Differenz und P-diff2 genau gleich sind, da sie mit unterschiedlichen Funktionen berechnet wurden
# Info: Aufgrund der Schreibweise von P-Differenz werden hier die Klammern benutzt, um die Spalte auszuwählen
msft['P-Differenz'].equals(msft.P_diff2)

True

In [ ]:
# Devision zweier Spalten minus 1 = relative Preisänderung

msft.Price.div(msft.P_lag1)-1

Date
2014-10-01       NaN
2014-10-02   -0.0030
2014-10-03    0.0072
2014-10-06    0.0000
2014-10-07   -0.0122
               ...
2021-05-24    0.0229
2021-05-25    0.0037
2021-05-26   -0.0009
2021-05-27   -0.0087
2021-05-28    0.0015
Length: 1677, dtype: float64