# Investment Multiple and CAGR (Compund Annual Growth Rate)

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.float_format='{:.2f}'.format

plt.style.use('seaborn-v0_8')
#print(plt.style.available)

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'petroff10', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']

In [2]:
msft=pd.read_csv('msft.csv')
msft

            Date  Price  Returns
0     2014-10-01  38.88      NaN
1     2014-10-02  38.76    -0.00
2     2014-10-03  39.04     0.01
3     2014-10-06  39.04     0.00
4     2014-10-07  38.57    -0.01
...          ...    ...      ...
1672  2021-05-24 241.74     0.02
1673  2021-05-25 242.65     0.00
1674  2021-05-26 242.43    -0.00
1675  2021-05-27 240.33    -0.01
1676  2021-05-28 240.68     0.00

[1677 rows x 3 columns]

In [3]:
msft=pd.read_csv('msft.csv', index_col='Date', parse_dates=True)
msft

            Price  Returns
Date
2014-10-01  38.88      NaN
2014-10-02  38.76    -0.00
2014-10-03  39.04     0.01
2014-10-06  39.04     0.00
2014-10-07  38.57    -0.01
...           ...      ...
2021-05-24 241.74     0.02
2021-05-25 242.65     0.00
2021-05-26 242.43    -0.00
2021-05-27 240.33    -0.01
2021-05-28 240.68     0.00

[1677 rows x 2 columns]