# Investment Multiple and CAGR (Compund Annual Growth Rate)

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.float_format='{:.4f}'.format

plt.style.use('seaborn-v0_8')
#print(plt.style.available)

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'petroff10', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']

In [12]:
msft=pd.read_csv('msft.csv')
msft

            Date    Price  Returns
0     2014-10-01  38.8802      NaN
1     2014-10-02  38.7616  -0.0031
2     2014-10-03  39.0411   0.0072
3     2014-10-06  39.0411   0.0000
4     2014-10-07  38.5668  -0.0121
...          ...      ...      ...
1672  2021-05-24 241.7445   0.0229
1673  2021-05-25 242.6507   0.0037
1674  2021-05-26 242.4289  -0.0009
1675  2021-05-27 240.3275  -0.0087
1676  2021-05-28 240.6841   0.0015

[1677 rows x 3 columns]

In [13]:
msft=pd.read_csv('msft.csv', index_col='Date', parse_dates=True)
msft

              Price  Returns
Date
2014-10-01  38.8802      NaN
2014-10-02  38.7616  -0.0031
2014-10-03  39.0411   0.0072
2014-10-06  39.0411   0.0000
2014-10-07  38.5668  -0.0121
...             ...      ...
2021-05-24 241.7445   0.0229
2021-05-25 242.6507   0.0037
2021-05-26 242.4289  -0.0009
2021-05-27 240.3275  -0.0087
2021-05-28 240.6841   0.0015

[1677 rows x 2 columns]

# Investment Multiple: Ending Value of 1 Dollar invested.
Multiple = Ending Value / Initial Investment

In [25]:
multiple=(msft.Price.iloc[-1]/msft.Price.iloc[0])
multiple

np.float64(6.190410313769353)

In [26]:
(multiple-1)*100
# An increase of 519.0410313769353 %

np.float64(519.0410313769353)

In [27]:
msft.Price/msft.Price.iloc[0] # similar/identical concept: Normalized Price with Base Value 1

Date
2014-10-01   1.0000
2014-10-02   0.9969
2014-10-03   1.0041
2014-10-06   1.0041
2014-10-07   0.9919
              ...
2021-05-24   6.2177
2021-05-25   6.2410
2021-05-26   6.2353
2021-05-27   6.1812
2021-05-28   6.1904
Name: Price, Length: 1677, dtype: float64

**Drawback of Investment Multiple:** Doesn´t take account into investment Perioad. Meaningful only in conjunction with Investmend Period.
**Compound Annual Growth Rate (CAGR):** The (constant annual) rate of return that would be required for an investment to grow from its beginning balance to its ending balance, assuming the profits were reinvested at the end of each year of the investment´s lifespan.

In [28]:
start=msft.index[0]
start

Timestamp('2014-10-01 00:00:00')

In [29]:
end=msft.index[-1]
end

Timestamp('2021-05-28 00:00:00')

In [30]:
# calculate the time difference (td)

td=end-start
td

Timedelta('2431 days 00:00:00')

In [31]:
td_years=td.days/365.25
td_years

6.655715263518139

In [35]:
# calculate the Compound Annual Growth Rate
cagr=multiple**(1/td_years)-1 #short version
cagr

np.float64(0.31508347709225926)

In [34]:
cagrII=(msft.Price.iloc[-1]/msft.Price.iloc[0])**(1/((msft.index[-1]-msft.index[0]).days/365.25))-1
cagrII

np.float64(0.31508347709225926)

In [36]:
(1+cagr)**td_years# alternative #2 to calculate multiple (cagr)

np.float64(6.19041031376935)

** -> CAGR can be used to compare Investments with different Investments horizon.**

# Compund Returns & Geometric Mean Return

In [38]:
multiple=(msft.Returns+1).prod()
multiple

np.float64(6.190410313769588)

In [39]:
n=msft.Returns.count()
n

np.int64(1676)

In [40]:
geo_mean=multiple**(1/n)-1 # Gemetric Mean return (daily)
geo_mean

np.float64(0.0010883014192786256)

In [41]:
(geo_mean+1)**n

np.float64(6.190410313769176)

In [42]:
mu=msft.Returns.mean() # arithmetic mean return
mu

np.float64(0.0012367321319832723)

**The arithmetic mean return is always greater than the gemoetric mean return... and less usefull**

In [43]:
(mu+1)**n # calculate multiple? not possible with arithmetic mean!

np.float64(7.936579449744636)

# Coding Challenge#3

- Calculate Boeing´s Investment Multiple
- Calculate CAGR
- Geometric Mean Return
- Calculate Investments Multiple with compound daily returns