# Coding Exercises

Now, you will have the opportunity to analyze your own dataset. <br>
__Follow the instructions__ and insert your code! You are either requested to 
- Complete the Code and __Fill in the gaps__. Gaps are marked with "__---__" and are __placeholders__ for your code fragment 
- Write Code completely __on your own__

In some exercises, you will find questions that can only be answered, if your code is correct and returns the right output! The correct answer is provided below your coding cell. There you can check whether your code is correct.

### Have Fun!

--------------------------------------------------------------------------------------------------------------

## Time Series Data in Pandas: Introduction


### Exercise 1: Intro to Time Series Data & DatetimeIndex

In [100]:
#run the cell!
import pandas as pd

1. __Import__ the csv-file "__aapl_fb.csv__" containing Stock Price Data for Apple and Facebook for the years 2015-2018! Convert the datatype in the column __Date__ to __datetime__ and set the column __Date__ as the __Index__ of the DataFrame! <br>
__Save__ the DataFrame in the variable __stocks__! __Fill in the gaps!__

In [101]:
stocks = pd.read_csv("aapl_fb.csv", sep = ',', index_col = "Date", parse_dates=['Date'])

How many Timestamps does __stocks__ contain? What was the __maximum stock price__ for Facebook in that Period?

In [102]:
# run the cell!
stocks

                  AAPL          FB
Date
2015-01-02  109.330002   78.449997
2015-01-05  106.250000   77.190002
2015-01-06  106.260002   76.150002
2015-01-07  107.750000   76.150002
2015-01-08  111.889999   78.180000
...                ...         ...
2018-12-21  150.729996  124.949997
2018-12-24  146.830002  124.059998
2018-12-26  157.169998  134.179993
2018-12-27  156.149994  134.520004
2018-12-28  156.229996  133.199997

[1005 rows x 2 columns]

In [103]:
# run the cell!
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1005 entries, 2015-01-02 to 2018-12-28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    1005 non-null   float64
 1   FB      1005 non-null   float64
dtypes: float64(2)
memory usage: 23.6 KB

In [104]:
# run the cell!
stocks.describe()

              AAPL           FB
count  1005.000000  1005.000000
mean    140.988338   133.415502
std      35.082112    35.846003
min      90.339996    74.050003
25%     112.120003   105.019997
50%     129.360001   129.070007
75%     168.630005   167.410004
max     232.070007   217.500000

There are in total ... 1005 Timestamps with stock price data. Facebooks´s maximum stock price was ... 217.50!

2. __Select__ the stock prices on __May 13, 2016__! What was the Price for __Apple__?

In [27]:
stocks.loc['2016-05-13']

AAPL     90.519997
FB      119.809998
Name: 2016-05-13 00:00:00, dtype: float64

The Apple Stock Price on that day was ... 90.52

3. __Select__ all stock prices in __September 2017__ and calculate the __mean__ for both stocks! What was the __mean stock price__ for __Apple__ in __September 2017__?

In [105]:
stocks.loc['2017-09'].mean()

AAPL    157.6085
FB      170.5910
dtype: float64

Apple´s monthly mean price for September 2017 is ... 157.61!

4. __Create a Timestamp__ for August 10, 2019! (convert __2 alternative date strings__ of your choice)

In [33]:
# Alt 1
pd.to_datetime('2019-08-10')

Timestamp('2019-08-10 00:00:00')

In [106]:
# Alt 2
pd.to_datetime('2019/08/10')

Timestamp('2019-08-10 00:00:00')

In [107]:

pd.to_datetime('10 August 2019')

Timestamp('2019-08-10 00:00:00')

5. __Change Frequency__ of stocks to __monthly__ ("Downsampling") and display the __last__ traded stock price per month! (Hint: The Index should show the last calender day of each month) <br>
What is the __last__ traded price for __Facebook__ in __March 2015__?

In [125]:
stocks.resample('ME').last()

                  AAPL          FB
Date
2015-01-31  117.160004   75.910004
2015-02-28  128.460007   78.970001
2015-03-31  124.430000   82.220001
2015-04-30  125.150002   78.769997
2015-05-31  130.279999   79.190002
2015-06-30  125.430000   85.769997
2015-07-31  121.300003   94.010002
2015-08-31  112.760002   89.430000
2015-09-30  110.300003   89.900002
2015-10-31  119.500000  101.970001
2015-11-30  118.300003  104.239998
2015-12-31  105.260002  104.660004
2016-01-31   97.339996  112.209999
2016-02-29   96.690002  106.919998
2016-03-31  108.989998  114.099998
2016-04-30   93.739998  117.580002
2016-05-31   99.860001  118.809998
2016-06-30   95.599998  114.279999
2016-07-31  104.209999  123.940002
2016-08-31  106.099998  126.120003
2016-09-30  113.050003  128.270004
2016-10-31  113.540001  130.990005
2016-11-30  110.519997  118.419998
2016-12-31  115.820000  115.050003
2017-01-31  121.349998  130.320007
2017-02-28  136.990005  135.539993
2017-03-31  143.660004  142.050003
2017-04-30  143.649994  150.250000
2017-05-31  152.759995  151.460007
2017-06-30  144.020004  150.979996
2017-07-31  148.729996  169.250000
2017-08-31  164.000000  171.970001
2017-09-30  154.119995  170.869995
2017-10-31  169.039993  180.059998
2017-11-30  171.850006  177.179993
2017-12-31  169.229996  176.460007
2018-01-31  167.429993  186.889999
2018-02-28  178.119995  178.320007
2018-03-31  167.779999  159.789993
2018-04-30  165.259995  172.000000
2018-05-31  186.869995  191.779999
2018-06-30  185.110001  194.320007
2018-07-31  190.289993  172.580002
2018-08-31  227.630005  175.729996
2018-09-30  225.740005  164.460007
2018-10-31  218.860001  151.789993
2018-11-30  178.580002  140.610001
2018-12-31  156.229996  133.199997

In [147]:
stocks_m=stocks.resample('ME').mean()

In [42]:
stocks.head()

                  AAPL         FB
Date
2015-01-02  109.330002  78.449997
2015-01-05  106.250000  77.190002
2015-01-06  106.260002  76.150002
2015-01-07  107.750000  76.150002
2015-01-08  111.889999  78.180000

In [79]:
stocks.resample('ME').last()

                  AAPL          FB
Date
2015-01-31  117.160004   75.910004
2015-02-28  128.460007   78.970001
2015-03-31  124.430000   82.220001
2015-04-30  125.150002   78.769997
2015-05-31  130.279999   79.190002
2015-06-30  125.430000   85.769997
2015-07-31  121.300003   94.010002
2015-08-31  112.760002   89.430000
2015-09-30  110.300003   89.900002
2015-10-31  119.500000  101.970001
2015-11-30  118.300003  104.239998
2015-12-31  105.260002  104.660004
2016-01-31   97.339996  112.209999
2016-02-29   96.690002  106.919998
2016-03-31  108.989998  114.099998
2016-04-30   93.739998  117.580002
2016-05-31   99.860001  118.809998
2016-06-30   95.599998  114.279999
2016-07-31  104.209999  123.940002
2016-08-31  106.099998  126.120003
2016-09-30  113.050003  128.270004
2016-10-31  113.540001  130.990005
2016-11-30  110.519997  118.419998
2016-12-31  115.820000  115.050003
2017-01-31  121.349998  130.320007
2017-02-28  136.990005  135.539993
2017-03-31  143.660004  142.050003
2017-04-30  143.649994  150.250000
2017-05-31  152.759995  151.460007
2017-06-30  144.020004  150.979996
2017-07-31  148.729996  169.250000
2017-08-31  164.000000  171.970001
2017-09-30  154.119995  170.869995
2017-10-31  169.039993  180.059998
2017-11-30  171.850006  177.179993
2017-12-31  169.229996  176.460007
2018-01-31  167.429993  186.889999
2018-02-28  178.119995  178.320007
2018-03-31  167.779999  159.789993
2018-04-30  165.259995  172.000000
2018-05-31  186.869995  191.779999
2018-06-30  185.110001  194.320007
2018-07-31  190.289993  172.580002
2018-08-31  227.630005  175.729996
2018-09-30  225.740005  164.460007
2018-10-31  218.860001  151.789993
2018-11-30  178.580002  140.610001
2018-12-31  156.229996  133.199997

The last traded price is ... 82.22!

6. Calculate __monthly average/mean stock prices__ and save the new DataFrame in the variable __stocks_m__!

In [146]:
stocks_m=stocks.resample('ME').mean()

What was the average stock price for __Facebook__ in __April 2015__?

In [148]:
# run the cell!
stocks_m.head()

                  AAPL         FB
Date
2015-01-31  110.641501  76.721500
2015-02-28  125.432105  76.951053
2015-03-31  125.970908  81.013183
2015-04-30  127.291428  82.091428
2015-05-31  128.761500  79.420000

The average price in april is ... 82.09!

7. __Downsample__ stocks to __weekly__ frequency, showing prices on __Fridays__!
What was __Facebook´s__ stock price on the __fourth Friday__ in __January 2015__?

In [149]:
stocks_m=stocks.resample('W-Fri').last()

Facebook´s stock price on the fourth Friday in January 2015 was ... 77.83!

In [150]:
stocks_m.head()

                  AAPL         FB
Date
2015-01-02  109.330002  78.449997
2015-01-09  112.010002  77.739998
2015-01-16  105.989998  75.180000
2015-01-23  112.980003  77.830002
2015-01-30  117.160004  75.910004

# Solutions (Stop here if you want to code on your own!)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Time Series Data in Pandas: Introduction


### Exercise 1: Intro to Time Series Data & DatetimeIndex

In [81]:
#run the cell!
import pandas as pd

1. __Import__ the csv-file "__aapl_fb.csv__" containing Stock Price Data for Apple and Facebook for the years 2015-2018! Convert the datatype in the column __Date__ to __datetime__ and set the column __Date__ as the __Index__ of the DataFrame! <br>
__Save__ the DataFrame in the variable __stocks__! __Fill in the gaps!__

In [82]:
stocks = pd.read_csv("aapl_fb.csv", parse_dates= ["Date"], index_col = "Date")

How many Timestamps does __stocks__ contain? What was the __maximum stock price__ for Facebook in that Period?

In [83]:
# run the cell!
stocks.head()

                  AAPL         FB
Date
2015-01-02  109.330002  78.449997
2015-01-05  106.250000  77.190002
2015-01-06  106.260002  76.150002
2015-01-07  107.750000  76.150002
2015-01-08  111.889999  78.180000

In [84]:
# run the cell!
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1005 entries, 2015-01-02 to 2018-12-28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    1005 non-null   float64
 1   FB      1005 non-null   float64
dtypes: float64(2)
memory usage: 23.6 KB

In [85]:
# run the cell!
stocks.describe()

              AAPL           FB
count  1005.000000  1005.000000
mean    140.988338   133.415502
std      35.082112    35.846003
min      90.339996    74.050003
25%     112.120003   105.019997
50%     129.360001   129.070007
75%     168.630005   167.410004
max     232.070007   217.500000

There are in total ... 1005 Timestamps with stock price data. Facebooks´s maximum stock price was ... 217.50!

2. __Select__ the stock prices on __May 13, 2016__! What was the Price for __Apple__?

In [86]:
stocks.loc["2016-05-13"]

AAPL     90.519997
FB      119.809998
Name: 2016-05-13 00:00:00, dtype: float64

The Apple Stock Price on that day was ... 90.52

3. __Select__ all stock prices in __September 2017__ and calculate the __mean__ for both stocks! What was the __mean stock price__ for __Apple__ in __September 2017__?

In [87]:
stocks.loc["2017-09"].mean()

AAPL    157.6085
FB      170.5910
dtype: float64

Apple´s monthly mean price for September 2017 is ... 157.61!

4. __Create a Timestamp__ for August 10, 2019! (convert __2 alternative date strings__ of your choice)

In [88]:
# Alt 1
pd.to_datetime("2019-08-10")

Timestamp('2019-08-10 00:00:00')

In [89]:
# Alt 2
pd.to_datetime("10 Aug 2019")

Timestamp('2019-08-10 00:00:00')

5. __Change Frequency__ of stocks to __monthly__ ("Downsampling") and display the __last__ traded stock price per month! (Hint: The Index should show the last calender day of each month) <br>
What is the __last__ traded price for __Facebook__ in __March 2015__?

In [90]:
stocks.resample("M").last() # old

C:\Users\bedla\AppData\Local\Temp\ipykernel_10992\1690053823.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  stocks.resample("M").last() # old

                  AAPL          FB
Date
2015-01-31  117.160004   75.910004
2015-02-28  128.460007   78.970001
2015-03-31  124.430000   82.220001
2015-04-30  125.150002   78.769997
2015-05-31  130.279999   79.190002
2015-06-30  125.430000   85.769997
2015-07-31  121.300003   94.010002
2015-08-31  112.760002   89.430000
2015-09-30  110.300003   89.900002
2015-10-31  119.500000  101.970001
2015-11-30  118.300003  104.239998
2015-12-31  105.260002  104.660004
2016-01-31   97.339996  112.209999
2016-02-29   96.690002  106.919998
2016-03-31  108.989998  114.099998
2016-04-30   93.739998  117.580002
2016-05-31   99.860001  118.809998
2016-06-30   95.599998  114.279999
2016-07-31  104.209999  123.940002
2016-08-31  106.099998  126.120003
2016-09-30  113.050003  128.270004
2016-10-31  113.540001  130.990005
2016-11-30  110.519997  118.419998
2016-12-31  115.820000  115.050003
2017-01-31  121.349998  130.320007
2017-02-28  136.990005  135.539993
2017-03-31  143.660004  142.050003
2017-04-30  143.649994  150.250000
2017-05-31  152.759995  151.460007
2017-06-30  144.020004  150.979996
2017-07-31  148.729996  169.250000
2017-08-31  164.000000  171.970001
2017-09-30  154.119995  170.869995
2017-10-31  169.039993  180.059998
2017-11-30  171.850006  177.179993
2017-12-31  169.229996  176.460007
2018-01-31  167.429993  186.889999
2018-02-28  178.119995  178.320007
2018-03-31  167.779999  159.789993
2018-04-30  165.259995  172.000000
2018-05-31  186.869995  191.779999
2018-06-30  185.110001  194.320007
2018-07-31  190.289993  172.580002
2018-08-31  227.630005  175.729996
2018-09-30  225.740005  164.460007
2018-10-31  218.860001  151.789993
2018-11-30  178.580002  140.610001
2018-12-31  156.229996  133.199997

In [91]:
stocks.resample("ME").last() # NEW (Pandas 3.x)

                  AAPL          FB
Date
2015-01-31  117.160004   75.910004
2015-02-28  128.460007   78.970001
2015-03-31  124.430000   82.220001
2015-04-30  125.150002   78.769997
2015-05-31  130.279999   79.190002
2015-06-30  125.430000   85.769997
2015-07-31  121.300003   94.010002
2015-08-31  112.760002   89.430000
2015-09-30  110.300003   89.900002
2015-10-31  119.500000  101.970001
2015-11-30  118.300003  104.239998
2015-12-31  105.260002  104.660004
2016-01-31   97.339996  112.209999
2016-02-29   96.690002  106.919998
2016-03-31  108.989998  114.099998
2016-04-30   93.739998  117.580002
2016-05-31   99.860001  118.809998
2016-06-30   95.599998  114.279999
2016-07-31  104.209999  123.940002
2016-08-31  106.099998  126.120003
2016-09-30  113.050003  128.270004
2016-10-31  113.540001  130.990005
2016-11-30  110.519997  118.419998
2016-12-31  115.820000  115.050003
2017-01-31  121.349998  130.320007
2017-02-28  136.990005  135.539993
2017-03-31  143.660004  142.050003
2017-04-30  143.649994  150.250000
2017-05-31  152.759995  151.460007
2017-06-30  144.020004  150.979996
2017-07-31  148.729996  169.250000
2017-08-31  164.000000  171.970001
2017-09-30  154.119995  170.869995
2017-10-31  169.039993  180.059998
2017-11-30  171.850006  177.179993
2017-12-31  169.229996  176.460007
2018-01-31  167.429993  186.889999
2018-02-28  178.119995  178.320007
2018-03-31  167.779999  159.789993
2018-04-30  165.259995  172.000000
2018-05-31  186.869995  191.779999
2018-06-30  185.110001  194.320007
2018-07-31  190.289993  172.580002
2018-08-31  227.630005  175.729996
2018-09-30  225.740005  164.460007
2018-10-31  218.860001  151.789993
2018-11-30  178.580002  140.610001
2018-12-31  156.229996  133.199997

The last traded price is ... 82.22!

6. Calculate __monthly average/mean stock prices__ and save the new DataFrame in the variable __stocks_m__!

In [93]:
stocks_m  = stocks.resample("M").mean() # NEW

C:\Users\bedla\AppData\Local\Temp\ipykernel_10992\3464350708.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  stocks_m  = stocks.resample("M").mean() # NEW

What was the average stock price for __Facebook__ in __April 2015__?

In [ ]:
# run the cell!
stocks_m.head()

The average price in april is ... 82.09!

7. __Downsample__ stocks to __weekly__ frequency, showing prices on __Fridays__!
What was __Facebook´s__ stock price on the __fourth Friday__ in __January 2015__?

In [99]:
stocks_last=stocks.resample("ME")
stocks_last.sum()

                   AAPL           FB
Date
2015-01-31  2212.830017  1534.430002
2015-02-28  2383.209991  1462.069999
2015-03-31  2771.359984  1782.290016
2015-04-30  2673.119979  1723.919992
2015-05-31  2575.229995  1588.400008
2015-06-30  2811.749984  1832.240013
2015-07-31  2757.380006  2025.210005
2015-08-31  2381.290009  1927.350005
2015-09-30  2368.749995  1920.370011
2015-10-31  2493.920000  2136.849999
2015-11-30  2363.249993  2119.379991
2015-12-31  2457.989998  2318.250008
2016-01-31  1870.149977  1880.660017
2016-02-29  1914.929998  2118.419999
2016-03-31  2293.880005  2437.169996
2016-04-30  2241.520004  2350.619993
2016-05-31  1994.469993  2487.759973
2016-06-30  2125.690001  2536.130005
2016-07-31  1971.129996  2383.549995
2016-08-31  2476.300017  2862.790011
2016-09-30  2327.999992  2698.780004
2016-10-31  2429.850005  2723.900028
2016-11-30  2313.239991  2534.379990
2016-12-31  2401.050004  2478.879991
2017-01-31  2391.399995  2536.349984
2017-02-28  2540.569977  2542.779982
2017-03-31  3234.210005  3206.389997
2017-04-30  2714.849990  2716.339996
2017-05-31  3349.009981  3305.150040
2017-06-30  3252.289963  3345.750000
2017-07-31  2965.989990  3210.649979
2017-08-31  3657.490037  3890.680008
2017-09-30  3152.169999  3411.819993
2017-10-31  3471.979996  3812.750030
2017-11-30  3620.530013  3773.630005
2017-12-31  3437.830001  3548.330001
2018-01-31  3654.109987  3884.219984
2018-02-28  3185.139998  3425.119998
2018-03-31  3664.420026  3643.279968
2018-04-30  3566.520017  3440.020003
2018-05-31  4081.809998  4024.460006
2018-06-30  3961.050004  4100.620009
2018-07-31  3996.540010  4199.309982
2018-08-31  4906.960036  4082.319948
2018-09-30  4219.400023  3123.170000
2018-10-31  5079.449997  3546.319990
2018-11-30  4015.949996  2974.350008
2018-12-31  2963.320021  2474.969987

Facebook´s stock price on the fourth Friday in January 2015 was ... 77.83!

# Well Done!

-------------------