## Machine Learning Strategies (1) - Model Fitting/Modellanpassung

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier # added (from sklearn v. 1.7)
import tpqoa
from datetime import datetime, timezone, timedelta
import time
import pickle
import warnings
warnings.filterwarnings('ignore')

In [3]:
api = tpqoa.tpqoa(r'C:\Users\bedla\Documents\Ausbildung_Informatik\1_Praktikum\Praktikum_Daten-_und_Prozessanalyse\energy_trading\PyCharm_Notebook\Trading\Data\oanda.cfg')

In [4]:
### Zeitintervalle ###
# S5, S10, S15, S30 (Sekunden)

# M1, M2, M4, M5, M10, M15, M30 (Minuten)

# H1, H2, H3, H4, H6, H8, H12 (Stunden)

# D (Tag), W (Woche), M (Monat)

data=api.get_history(instrument = 'EUR_USD', start = '2025-06-01', end = '2026-01-14', granularity = 'M5', price = 'M')

In [5]:
data

                           o        h        l        c  volume  complete
time
2025-06-01 21:00:00  1.13491  1.13491  1.13491  1.13491       1      True
2025-06-01 21:05:00  1.13487  1.13491  1.13470  1.13470      32      True
2025-06-01 21:10:00  1.13470  1.13494  1.13470  1.13491      50      True
2025-06-01 21:15:00  1.13492  1.13493  1.13486  1.13490      27      True
2025-06-01 21:20:00  1.13488  1.13490  1.13486  1.13488       8      True
...                      ...      ...      ...      ...     ...       ...
2026-01-13 23:35:00  1.16450  1.16456  1.16446  1.16450      54      True
2026-01-13 23:40:00  1.16448  1.16448  1.16431  1.16434     141      True
2026-01-13 23:45:00  1.16436  1.16440  1.16432  1.16436      43      True
2026-01-13 23:50:00  1.16436  1.16440  1.16426  1.16426      99      True
2026-01-13 23:55:00  1.16426  1.16429  1.16420  1.16420      69      True

[46101 rows x 6 columns]

In [6]:
data.drop(['o','h','l','volume','complete'], axis=1, inplace=True)

In [7]:
data

                           c
time
2025-06-01 21:00:00  1.13491
2025-06-01 21:05:00  1.13470
2025-06-01 21:10:00  1.13491
2025-06-01 21:15:00  1.13490
2025-06-01 21:20:00  1.13488
...                      ...
2026-01-13 23:35:00  1.16450
2026-01-13 23:40:00  1.16434
2026-01-13 23:45:00  1.16436
2026-01-13 23:50:00  1.16426
2026-01-13 23:55:00  1.16420

[46101 rows x 1 columns]

In [8]:
data.rename(columns={"c": "price"}, inplace=True)

In [9]:
data

                       price
time
2025-06-01 21:00:00  1.13491
2025-06-01 21:05:00  1.13470
2025-06-01 21:10:00  1.13491
2025-06-01 21:15:00  1.13490
2025-06-01 21:20:00  1.13488
...                      ...
2026-01-13 23:35:00  1.16450
2026-01-13 23:40:00  1.16434
2026-01-13 23:45:00  1.16436
2026-01-13 23:50:00  1.16426
2026-01-13 23:55:00  1.16420

[46101 rows x 1 columns]

In [10]:
data.to_csv(r'C:\Users\bedla\Documents\Ausbildung_Informatik\1_Praktikum\Praktikum_Daten-_und_Prozessanalyse\energy_trading\PyCharm_Notebook\Trading\Data\20260114_five_minute.csv')