# Appendix 3: Python Libraries Crash Course

## Part 3: Pandas for Tabular Data

### Creating your very first Pandas DataFrame (from csv)

In [1]:
import pandas as pd

In [2]:
pd.read_csv("titanic.csv")

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [3]:
titanic = pd.read_csv("titanic.csv")

In [4]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

### Pandas Display Options and the methods head() & tail()

In [5]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [6]:
print(titanic)

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [7]:
pd.options.display.max_rows

60

In [8]:
pd.options.display.min_rows

10

In [9]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [10]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [11]:
titanic.head(20)

    survived  pclass     sex   age  sibsp  parch     fare embarked deck
0          0       3    male  22.0      1      0   7.2500        S  NaN
1          1       1  female  38.0      1      0  71.2833        C    C
2          1       3  female  26.0      0      0   7.9250        S  NaN
3          1       1  female  35.0      1      0  53.1000        S    C
4          0       3    male  35.0      0      0   8.0500        S  NaN
5          0       3    male   NaN      0      0   8.4583        Q  NaN
6          0       1    male  54.0      0      0  51.8625        S    E
7          0       3    male   2.0      3      1  21.0750        S  NaN
8          1       3  female  27.0      0      2  11.1333        S  NaN
9          1       2  female  14.0      1      0  30.0708        C  NaN
10         1       3  female   4.0      1      1  16.7000        S    G
11         1       1  female  58.0      0      0  26.5500        S    C
12         0       3    male  20.0      0      0   8.0500        S  NaN
13         0       3    male  39.0      1      5  31.2750        S  NaN
14         0       3  female  14.0      0      0   7.8542        S  NaN
15         1       2  female  55.0      0      0  16.0000        S  NaN
16         0       3    male   2.0      4      1  29.1250        Q  NaN
17         1       2    male   NaN      0      0  13.0000        S  NaN
18         0       3  female  31.0      1      0  18.0000        S  NaN
19         1       3  female   NaN      0      0   7.2250        C  NaN

In [12]:
titanic.tail()

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [13]:
titanic.tail(2)

     survived  pclass   sex   age  sibsp  parch   fare embarked deck
889         1       1  male  26.0      0      0  30.00        C    C
890         0       3  male  32.0      0      0   7.75        Q  NaN

### First Data Inspection

In [14]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [15]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [16]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
titanic.describe(include = "O")

         sex embarked deck
count    891      889  203
unique     2        3    7
top     male        S    C
freq     577      644   59

### Python Built-in Functions & DataFrame Attributes and Methods

In [18]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

#### DataFrames and Python Built-in Functions

In [19]:
type(titanic)

pandas.core.frame.DataFrame

In [20]:
len(titanic)

891

In [21]:
round(titanic, 0)

     survived  pclass     sex   age  sibsp  parch  fare embarked deck
0           0       3    male  22.0      1      0   7.0        S  NaN
1           1       1  female  38.0      1      0  71.0        C    C
2           1       3  female  26.0      0      0   8.0        S  NaN
3           1       1  female  35.0      1      0  53.0        S    C
4           0       3    male  35.0      0      0   8.0        S  NaN
..        ...     ...     ...   ...    ...    ...   ...      ...  ...
886         0       2    male  27.0      0      0  13.0        S  NaN
887         1       1  female  19.0      0      0  30.0        S    B
888         0       3  female   NaN      1      2  23.0        S  NaN
889         1       1    male  26.0      0      0  30.0        C    C
890         0       3    male  32.0      0      0   8.0        Q  NaN

[891 rows x 9 columns]

In [ ]:
#int(titanic)

In [22]:
min(titanic)

'age'

#### DataFrame Attributes

In [23]:
titanic.shape

(891, 9)

In [24]:
titanic.size

8019

In [25]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [26]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

#### DataFrame Methods

In [29]:
titanic.head(2)

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C

In [30]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [ ]:
# titanic.min() # old

In [34]:
titanic.min(numeric_only = True) # new

survived    0.00
pclass      1.00
age         0.42
sibsp       0.00
parch       0.00
fare        0.00
dtype: float64

#### Method Chaining

In [ ]:
# titanic.mean().sort_values().head(2) # old

In [35]:
titanic.mean(numeric_only = True).sort_values().head(2) # new

parch       0.381594
survived    0.383838
dtype: float64

### Selecting Columns

In [31]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [32]:
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [33]:
type(titanic["age"])

pandas.core.series.Series

In [38]:
#titanic["age", "sex"]

KeyError: ('age', 'sex')

In [36]:
titanic[["age", "sex"]]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [39]:
type(titanic[["age", "sex"]])

pandas.core.frame.DataFrame

In [40]:
titanic[["sex", "age"]]

        sex   age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
886    male  27.0
887  female  19.0
888  female   NaN
889    male  26.0
890    male  32.0

[891 rows x 2 columns]

In [41]:
titanic[["sex", "age", "fare"]]

        sex   age     fare
0      male  22.0   7.2500
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
4      male  35.0   8.0500
..      ...   ...      ...
886    male  27.0  13.0000
887  female  19.0  30.0000
888  female   NaN  23.4500
889    male  26.0  30.0000
890    male  32.0   7.7500

[891 rows x 3 columns]

In [42]:
type(titanic[["age"]])

pandas.core.frame.DataFrame

### Selecting one Column with "dot notation"

In [43]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [44]:
titanic.age.equals(titanic["age"])

True

In [ ]:
titanic.embarked

### Position-based Indexing and Slicing with iloc[]

In [45]:
import pandas as pd

In [47]:
summer = pd.read_csv("summer.csv", index_col = "Athlete")

In [48]:
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [49]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Country     31161 non-null  object
 5   Gender      31165 non-null  object
 6   Event       31165 non-null  object
 7   Medal       31165 non-null  object
dtypes: int64(1), object(7)
memory usage: 3.1+ MB

#### Selecting Rows with iloc[]

In [50]:
summer.iloc[0]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  HUN
Gender                   Men
Event         100M Freestyle
Medal                   Gold
Name: HAJOS, Alfred, dtype: object

In [51]:
type(summer.iloc[0])

pandas.core.series.Series

In [52]:
summer.iloc[1]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  AUT
Gender                   Men
Event         100M Freestyle
Medal                 Silver
Name: HERSCHMANN, Otto, dtype: object

In [53]:
summer.iloc[-1]

Year                         2012
City                       London
Sport                   Wrestling
Discipline    Wrestling Freestyle
Country                       SWE
Gender                        Men
Event                    Wg 96 KG
Medal                      Bronze
Name: LIDBERG, Jimmy, dtype: object

In [54]:
summer.iloc[[1, 2, 3]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold

In [55]:
summer.iloc[1:4]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold

In [56]:
summer.iloc[:5]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [57]:
summer.iloc[-5:]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [58]:
summer.iloc[:]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [59]:
summer.iloc[[2, 45, 5467]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"PERSAKIS, Ioannis",1896,Athens,Athletics,Athletics,GRE,Men,Triple Jump,Bronze
"POLAK, Ans",1928,Amsterdam,Gymnastics,Artistic G.,NED,Women,Team Competition,Gold

#### Indexing/Slicing Rows and Columns with iloc[]

In [ ]:
summer.head(10)

In [ ]:
summer.iloc[0, 4]

In [ ]:
summer.iloc[0, :3]

In [ ]:
summer.iloc[0, [0, 2, 5, 7]]

In [ ]:
summer.iloc[34:39, [0, 2, 5, 7]]

#### Selecting Columns with iloc[]

In [ ]:
summer.iloc[:, 4].equals(summer.Country)

In [ ]:
summer["Country"]

### Label-based Indexing and Slicing with loc[]

In [ ]:
summer

#### Selecting Rows with loc[]

In [ ]:
summer.iloc[2]

In [ ]:
summer.loc["DRIVAS, Dimitrios"]

In [ ]:
summer.loc["PHELPS, Michael"]

#### Indexing/Slicing Rows and Columns with loc[]

In [ ]:
summer.loc["PHELPS, Michael", "Medal"]

In [ ]:
summer.loc["PHELPS, Michael", ["Medal", "Event"]]

In [ ]:
summer.loc[["PHELPS, Michael", "LEWIS, Carl"], ["Medal", "Event"]]

In [ ]:
summer.loc[:, ["Medal", "Event"]]

In [ ]:
summer.head(10)

In [ ]:
summer.loc[:"CHASAPIS, Spiridon"]

In [ ]:
#summer.loc[:"PHELPS, Michael"]

In [ ]:
#summer.loc["PHELPS, Michael":]

In [ ]:
summer.head(20)

In [ ]:
summer.loc["DRIVAS, Dimitrios":"BLAKE, Arthur", "City":"Discipline"]

In [ ]:
#summer.loc[["PHELPS, Michael", "DUCK, Donald"]]

In [ ]:
#summer.loc["PHELPS, Michael", ["Year", "Age"]]

### Summary and Outlook

#### Importing from CSV and first Inspection

In [ ]:
import pandas as pd

In [ ]:
summer = pd.read_csv("summer.csv", index_col = "Athlete")

In [ ]:
summer

In [ ]:
summer.info()

#### Selecting one Column

In [ ]:
summer.Medal

In [ ]:
summer["Medal"]

#### Selecting multiple Columns

In [ ]:
summer[["Year", "Medal"]]

In [ ]:
summer.loc[:, ["Year", "Medal"]]

#### Selecting positional rows

In [ ]:
summer.iloc[10:21]

#### Selecting labeled rows

In [ ]:
summer.loc["LEWIS, Carl"]

#### Putting it all together

In [ ]:
summer[["Year", "Event", "Medal"]].loc["LEWIS, Carl"]

In [ ]:
summer.loc["LEWIS, Carl"][["Year", "Event", "Medal"]]

In [ ]:
summer.loc["LEWIS, Carl", ["Year", "Event", "Medal"]]

#### Outlook Pandas Objects

In [ ]:
summer

In [ ]:
type(summer)

In [ ]:
summer["Year"]

In [ ]:
type(summer["Year"])

In [ ]:
summer.columns

In [ ]:
type(summer.columns)

In [ ]:
summer.index

In [ ]:
type(summer.index)