# Appendix 3: Python Libraries Crash Course

## Part 5: Pandas Intermediate 2

## Filtering DataFrames with one Condition

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv("titanic.csv")

In [3]:
titanic.head(10)

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN
5         0       3    male   NaN      0      0   8.4583        Q  NaN
6         0       1    male  54.0      0      0  51.8625        S    E
7         0       3    male   2.0      3      1  21.0750        S  NaN
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [4]:
titanic.sex.head(10)

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: sex, dtype: object

In [5]:
titanic.sex == "male"

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: sex, Length: 891, dtype: bool

In [111]:
titanic[titanic.sex == "male"]

     survived  pclass   sex   age  sibsp  parch     fare embarked deck
0           0       3  male  22.0      1      0   7.2500        S  NaN
4           0       3  male  35.0      0      0   8.0500        S  NaN
5           0       3  male   NaN      0      0   8.4583        Q  NaN
6           0       1  male  54.0      0      0  51.8625        S    E
7           0       3  male   2.0      3      1  21.0750        S  NaN
..        ...     ...   ...   ...    ...    ...      ...      ...  ...
883         0       2  male  28.0      0      0  10.5000        S  NaN
884         0       3  male  25.0      0      0   7.0500        S  NaN
886         0       2  male  27.0      0      0  13.0000        S  NaN
889         1       1  male  26.0      0      0  30.0000        C    C
890         0       3  male  32.0      0      0   7.7500        Q  NaN

[577 rows x 9 columns]

In [6]:
# Chained Indexing - nicht empfohlen, da das DataFrame unfreiwillig geändert werden könnte

titanic[titanic.sex == "male"]["fare"]

0       7.2500
4       8.0500
5       8.4583
6      51.8625
7      21.0750
        ...
883    10.5000
884     7.0500
886    13.0000
889    30.0000
890     7.7500
Name: fare, Length: 577, dtype: float64

In [7]:
# loc-Notation empfohlen gegenüber Chained Indexing, da es das DataFrame nicht ändert

titanic.loc[titanic.sex == "male", "fare"]

0       7.2500
4       8.0500
5       8.4583
6      51.8625
7      21.0750
        ...
883    10.5000
884     7.0500
886    13.0000
889    30.0000
890     7.7500
Name: fare, Length: 577, dtype: float64

In [8]:
mask1 = titanic.sex == "male"
mask1

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: sex, Length: 891, dtype: bool

In [115]:
titanic.loc[titanic.sex == "male"].head()

   survived  pclass   sex   age  sibsp  parch     fare embarked deck
0         0       3  male  22.0      1      0   7.2500        S  NaN
4         0       3  male  35.0      0      0   8.0500        S  NaN
5         0       3  male   NaN      0      0   8.4583        Q  NaN
6         0       1  male  54.0      0      0  51.8625        S    E
7         0       3  male   2.0      3      1  21.0750        S  NaN

In [116]:
titanic_male = titanic.loc[mask1]
titanic_male.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [117]:
titanic.dtypes# == object

survived      int64
pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

In [118]:
mask2 = titanic.dtypes == object
mask2

survived    False
pclass      False
sex          True
age         False
sibsp       False
parch       False
fare        False
embarked     True
deck         True
dtype: bool

In [119]:
titanic.loc[:, ~mask2].head()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [120]:
titanic.loc[mask1, ~mask2].head()

   survived  pclass   age  sibsp  parch     fare
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
8         1       3  27.0      0      2  11.1333
9         1       2  14.0      1      0  30.0708

## Filtering DataFrames with many Conditions (AND)

In [15]:
import pandas as pd

In [16]:
titanic = pd.read_csv("titanic.csv")

In [17]:
titanic.head(10)

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN
5         0       3    male   NaN      0      0   8.4583        Q  NaN
6         0       1    male  54.0      0      0  51.8625        S    E
7         0       3    male   2.0      3      1  21.0750        S  NaN
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [18]:
mask1 = titanic.sex == "male"
mask1.head()

0     True
1    False
2    False
3    False
4     True
Name: sex, dtype: bool

In [121]:
mask2 = titanic.age > 14
mask2

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: age, Length: 891, dtype: bool

In [122]:
(mask1 & mask2)#.head()

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [126]:
male_adult = titanic.loc[mask1 & mask2, ["survived", "pclass", "sex", "age"]]
male_adult.head(20)

    survived  pclass     sex   age
1          1       1  female  38.0
2          1       3  female  26.0
3          1       1  female  35.0
8          1       3  female  27.0
11         1       1  female  58.0
15         1       2  female  55.0
18         0       3  female  31.0
22         1       3  female  15.0
25         1       3  female  38.0
38         0       3  female  18.0
40         0       3  female  40.0
41         0       2  female  27.0
44         1       3  female  19.0
49         0       3  female  18.0
52         1       1  female  49.0
53         1       2  female  29.0
56         1       2  female  21.0
61         1       1  female  38.0
66         1       2  female  29.0
68         1       3  female  17.0

In [22]:
male_adult.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 0
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 34.8+ KB

In [23]:
male_adult.describe()

       survived  pclass    age
count     891.0   891.0  891.0
mean        0.0     3.0   22.0
std         0.0     0.0    0.0
min         0.0     3.0   22.0
25%         0.0     3.0   22.0
50%         0.0     3.0   22.0
75%         0.0     3.0   22.0
max         0.0     3.0   22.0

In [24]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## Filtering DataFrames with many Conditions (OR)

In [25]:
import pandas as pd

In [26]:
titanic = pd.read_csv("titanic.csv")

In [27]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [128]:
mask1 = titanic.sex == "female"
mask1.head(11)

0     False
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8      True
9      True
10     True
Name: sex, dtype: bool

In [129]:
mask2 = titanic.age < 14
mask2.head(11)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
Name: age, dtype: bool

In [30]:
(mask1 | mask2).head(11)

0     False
1      True
2      True
3      True
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [127]:
titanic.loc[mask1 | mask2]

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[728 rows x 9 columns]

In [130]:
wom_or_chi = titanic.loc[mask1 | mask2, ["survived", "pclass", "sex", "age"]]

In [131]:
wom_or_chi.head()

   survived  pclass     sex   age
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
7         0       3    male   2.0
8         1       3  female  27.0

In [34]:
wom_or_chi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 351 entries, 1 to 888
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  351 non-null    int64
 1   pclass    351 non-null    int64
 2   sex       351 non-null    object
 3   age       298 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 13.7+ KB

In [132]:
wom_or_chi.describe()

         survived      pclass         age
count  351.000000  351.000000  298.000000
mean     0.723647    2.205128   25.039161
std      0.447832    0.847232   15.314631
min      0.000000    1.000000    0.420000
25%      0.000000    1.000000   14.125000
50%      1.000000    2.000000   24.000000
75%      1.000000    3.000000   35.000000
max      1.000000    3.000000   63.000000

In [36]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## Advanced Filtering with between(), isin() and ~

In [133]:
import pandas as pd

In [134]:
summer = pd.read_csv("summer.csv")

In [135]:
summer.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [147]:
summer

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [136]:
og_1988 = summer.loc[summer.Year == 1988]

In [137]:
og_1988.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
18051,1988,Seoul,Aquatics,Diving,"MENA CAMPOS, Jesus",MEX,Men,10M Platform,Bronze
18052,1988,Seoul,Aquatics,Diving,"LOUGANIS, Gregory",USA,Men,10M Platform,Gold
18053,1988,Seoul,Aquatics,Diving,"XIONG, Ni",CHN,Men,10M Platform,Silver
18054,1988,Seoul,Aquatics,Diving,"WYLAND-WILLIAMS, Wendy Lian",USA,Women,10M Platform,Bronze
18055,1988,Seoul,Aquatics,Diving,"XU, Yan-Mei",CHN,Women,10M Platform,Gold

In [42]:
og_1988.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
19592,1988,Seoul,Wrestling,Wrestling Gre-R,"KOMCHEV, Atanas Slavov",BUL,Men,82 - 90KG (Light-Heavyweight),Gold
19593,1988,Seoul,Wrestling,Wrestling Gre-R,"KOSKELA, Harri Matias",FIN,Men,82 - 90KG (Light-Heavyweight),Silver
19594,1988,Seoul,Wrestling,Wrestling Gre-R,"KOSLOWSKI, Dennis Marvin",USA,Men,90 - 100KG (Heavyweight),Bronze
19595,1988,Seoul,Wrestling,Wrestling Gre-R,"WRONSKI, Andrzej",POL,Men,90 - 100KG (Heavyweight),Gold
19596,1988,Seoul,Wrestling,Wrestling Gre-R,"HIMMEL, Gerhard",FRG,Men,90 - 100KG (Heavyweight),Silver

In [43]:
og_1988.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1546 entries, 18051 to 19596
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        1546 non-null   int64
 1   City        1546 non-null   object
 2   Sport       1546 non-null   object
 3   Discipline  1546 non-null   object
 4   Athlete     1546 non-null   object
 5   Country     1546 non-null   object
 6   Gender      1546 non-null   object
 7   Event       1546 non-null   object
 8   Medal       1546 non-null   object
dtypes: int64(1), object(8)
memory usage: 120.8+ KB

In [138]:
og_since1992 = summer.loc[summer.Year >= 1992]

In [139]:
og_since1992.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
19597,1992,Barcelona,Aquatics,Diving,"XIONG, Ni",CHN,Men,10M Platform,Bronze
19598,1992,Barcelona,Aquatics,Diving,"SUN, Shuwei",CHN,Men,10M Platform,Gold
19599,1992,Barcelona,Aquatics,Diving,"DONIE, Scott R.",USA,Men,10M Platform,Silver
19600,1992,Barcelona,Aquatics,Diving,"CLARK, Mary Ellen",USA,Women,10M Platform,Bronze
19601,1992,Barcelona,Aquatics,Diving,"FU, Mingxia",CHN,Women,10M Platform,Gold

In [46]:
og_since1992.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [145]:
summer.Year.between(1960, 1969)

0        False
1        False
2        False
3        False
4        False
         ...
31160    False
31161    False
31162    False
31163    False
31164    False
Name: Year, Length: 31165, dtype: bool

In [48]:
#og_60s = summer.loc[summer.Year.between(1960, 1969, inclusive=True)] # old

In [141]:
og_60s = summer.loc[summer.Year.between(1960, 1969, inclusive="both")] # new

In [142]:
og_60s.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
9792,1960,Rome,Aquatics,Diving,"PHELPS, Brian Eric",GBR,Men,10M Platform,Bronze
9793,1960,Rome,Aquatics,Diving,"WEBSTER, Robert David",USA,Men,10M Platform,Gold
9794,1960,Rome,Aquatics,Diving,"TOBIAN, Gary Milburn",USA,Men,10M Platform,Silver
9795,1960,Rome,Aquatics,Diving,"KRUTOVA, Ninel",URS,Women,10M Platform,Bronze
9796,1960,Rome,Aquatics,Diving,"KRÄMER-ENGEL-GULBIN, Ingrid",EUA,Women,10M Platform,Gold

In [143]:
og_60s.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
12710,1968,Mexico,Wrestling,Wrestling Gre-R,"METZ, Lothar",GDR,Men,78 - 87KG (Middleweight),Gold
12711,1968,Mexico,Wrestling,Wrestling Gre-R,"OLEINIK, Valentin",URS,Men,78 - 87KG (Middleweight),Silver
12712,1968,Mexico,Wrestling,Wrestling Gre-R,"MARTINESCU, Nicolae",ROU,Men,87 - 97KG (Light-Heavyweight),Bronze
12713,1968,Mexico,Wrestling,Wrestling Gre-R,"RADEV, Boyan Aleksandrov",BUL,Men,87 - 97KG (Light-Heavyweight),Gold
12714,1968,Mexico,Wrestling,Wrestling Gre-R,"YAKOVENKO, Nikolai",URS,Men,87 - 97KG (Light-Heavyweight),Silver

In [148]:
my_favourite_games = [1972, 1996]

In [151]:
summer.Year.isin(my_favourite_games).head(50)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Year, dtype: bool

In [54]:
og_72_96 = summer.loc[summer.Year.isin(my_favourite_games)]

In [55]:
og_72_96.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
12715,1972,Munich,Aquatics,Diving,"CAGNOTTO, Giorgio Franco",ITA,Men,10M Platform,Bronze
12716,1972,Munich,Aquatics,Diving,"DIBIASI, Klaus",ITA,Men,10M Platform,Gold
12717,1972,Munich,Aquatics,Diving,"RYDZE, Richard Anthony",USA,Men,10M Platform,Silver
12718,1972,Munich,Aquatics,Diving,"JANICKE, Marina",GDR,Women,10M Platform,Bronze
12719,1972,Munich,Aquatics,Diving,"KNAPE-LINDBERGH, Ulrika",SWE,Women,10M Platform,Gold

In [56]:
og_72_96.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
23156,1996,Atlanta,Wrestling,Wrestling Gre-R,"OLEYNYK, Vyacheslav",UKR,Men,82 - 90KG (Light-Heavyweight),Gold
23157,1996,Atlanta,Wrestling,Wrestling Gre-R,"FAFINSKI, Jacek",POL,Men,82 - 90KG (Light-Heavyweight),Silver
23158,1996,Atlanta,Wrestling,Wrestling Gre-R,"LJUNGBERG, Mikael",SWE,Men,90 - 100KG (Heavyweight),Bronze
23159,1996,Atlanta,Wrestling,Wrestling Gre-R,"WRONSKI, Andrzej",POL,Men,90 - 100KG (Heavyweight),Gold
23160,1996,Atlanta,Wrestling,Wrestling Gre-R,"LISHTVAN, Sergey",BLR,Men,90 - 100KG (Heavyweight),Silver

In [152]:
og_not_72_96 = summer.loc[~summer.Year.isin(my_favourite_games)]

In [153]:
og_not_72_96.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [154]:
og_not_72_96.Year.unique()

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1976, 1980, 1984, 1988, 1992, 2000,
       2004, 2008, 2012])

## Intro to NA Values

In [168]:
import pandas as pd
import numpy as np

In [169]:
sales = pd.read_csv("sales.csv", index_col=0)

In [170]:
sales

        Mon  Tue  Wed   Thu  Fri
Steven   34   27   15   NaN   33
Mike     45    9   74  87.0   12
Andi     17   33   54   8.0   29
Paul     87   67   27  45.0    7

In [63]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Steven to Paul
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Mon     4 non-null      int64
 1   Tue     4 non-null      int64
 2   Wed     4 non-null      int64
 3   Thu     3 non-null      float64
 4   Fri     4 non-null      int64
dtypes: float64(1), int64(4)
memory usage: 192.0+ bytes

In [64]:
sales.loc["Steven", "Thu"]

np.float64(nan)

In [65]:
sales.iloc[1,1] = None

In [66]:
sales

        Mon   Tue  Wed   Thu  Fri
Steven   34  27.0   15   NaN   33
Mike     45   NaN   74  87.0   12
Andi     17  33.0   54   8.0   29
Paul     87  67.0   27  45.0    7

In [67]:
sales.iloc[2,2] = np.nan

In [68]:
sales

        Mon   Tue   Wed   Thu  Fri
Steven   34  27.0  15.0   NaN   33
Mike     45   NaN  74.0  87.0   12
Andi     17  33.0   NaN   8.0   29
Paul     87  67.0  27.0  45.0    7

In [69]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Steven to Paul
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Mon     4 non-null      int64
 1   Tue     3 non-null      float64
 2   Wed     3 non-null      float64
 3   Thu     3 non-null      float64
 4   Fri     4 non-null      int64
dtypes: float64(3), int64(2)
memory usage: 364.0+ bytes

## Handling NA Values / missing Values

In [70]:
import pandas as pd

In [71]:
titanic = pd.read_csv("titanic.csv")

In [72]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [73]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [173]:
titanic.isna()

     survived  pclass    sex    age  sibsp  parch   fare  embarked   deck
0       False   False  False  False  False  False  False     False   True
1       False   False  False  False  False  False  False     False  False
2       False   False  False  False  False  False  False     False   True
3       False   False  False  False  False  False  False     False  False
4       False   False  False  False  False  False  False     False   True
..        ...     ...    ...    ...    ...    ...    ...       ...    ...
886     False   False  False  False  False  False  False     False   True
887     False   False  False  False  False  False  False     False  False
888     False   False  False   True  False  False  False     False   True
889     False   False  False  False  False  False  False     False  False
890     False   False  False  False  False  False  False     False   True

[891 rows x 9 columns]

In [171]:
titanic.isna().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [172]:
titanic.notna().sum()

survived    891
pclass      891
sex         891
age         714
sibsp       891
parch       891
fare        891
embarked    889
deck        203
dtype: int64

In [176]:
# side calculation

missing_val=titanic.notna().sum()+titanic.isna().sum()
missing_val

survived    891
pclass      891
sex         891
age         891
sibsp       891
parch       891
fare        891
embarked    891
deck        891
dtype: int64

In [177]:
titanic.loc[titanic.embarked.isna()]

     survived  pclass     sex   age  sibsp  parch  fare embarked deck
61          1       1  female  38.0      0      0  80.0      NaN    B
829         1       1  female  62.0      0      0  80.0      NaN    B

In [178]:
titanic.shape

(891, 9)

In [78]:
titanic.dropna()

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
6           0       1    male  54.0      0      0  51.8625        S    E
10          1       3  female   4.0      1      1  16.7000        S    G
11          1       1  female  58.0      0      0  26.5500        S    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
871         1       1  female  47.0      1      1  52.5542        S    D
872         0       1    male  33.0      0      0   5.0000        S    B
879         1       1  female  56.0      0      1  83.1583        C    C
887         1       1  female  19.0      0      0  30.0000        S    B
889         1       1    male  26.0      0      0  30.0000        C    C

[182 rows x 9 columns]

In [79]:
titanic.dropna().shape

(182, 9)

In [80]:
titanic.dropna(how = "all").shape

(891, 9)

In [81]:
titanic.dropna(axis = 1, how = "any").shape

(891, 6)

In [82]:
titanic.dropna(axis = 1, thresh = 500).shape

(891, 8)

In [83]:
titanic.dropna(axis = 1, thresh = 500, inplace = True)

In [84]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [85]:
titanic.loc[titanic.age.isna()]

     survived  pclass     sex  age  sibsp  parch     fare embarked
5           0       3    male  NaN      0      0   8.4583        Q
17          1       2    male  NaN      0      0  13.0000        S
19          1       3  female  NaN      0      0   7.2250        C
26          0       3    male  NaN      0      0   7.2250        C
28          1       3  female  NaN      0      0   7.8792        Q
..        ...     ...     ...  ...    ...    ...      ...      ...
859         0       3    male  NaN      0      0   7.2292        C
863         0       3  female  NaN      8      2  69.5500        S
868         0       3    male  NaN      0      0   9.5000        S
878         0       3    male  NaN      0      0   7.8958        S
888         0       3  female  NaN      1      2  23.4500        S

[177 rows x 8 columns]

In [86]:
mean_age = titanic.age.mean()
mean_age

np.float64(29.69911764705882)

In [87]:
# titanic.age.fillna(value = mean_age, inplace = True) # old

In [88]:
titanic["age"] = titanic["age"].fillna(value = mean_age) # new

In [89]:
titanic.age

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [90]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

## Exporting DataFrames to csv

In [91]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [92]:
titanic.to_csv("clean_df.csv", index = False)

In [93]:
pd.read_csv("clean_df.csv")

     survived  pclass     sex        age  sibsp  parch     fare embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

## Summary Statistics and Accumulations

In [94]:
import pandas as pd

In [95]:
titanic = pd.read_csv("titanic.csv")

In [96]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [97]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [98]:
titanic.count(axis = "columns")

0      8
1      9
2      8
3      9
4      8
      ..
886    8
887    9
888    7
889    9
890    8
Length: 891, dtype: int64

In [99]:
titanic.count(axis = 1)

0      8
1      9
2      8
3      9
4      8
      ..
886    8
887    9
888    7
889    9
890    8
Length: 891, dtype: int64

In [100]:
#titanic.mean(axis = 1) # old

In [101]:
titanic.mean(axis = 1, numeric_only=True) # new

0       5.541667
1      18.713883
2       6.320833
3      15.183333
4       7.675000
         ...
886     7.000000
887     8.500000
888     5.890000
889     9.666667
890     7.125000
Length: 891, dtype: float64

In [102]:
#titanic.sum(axis = 0) # old

In [103]:
titanic.sum(axis = 0, numeric_only=True) # new

survived      342.0000
pclass       2057.0000
age         21205.1700
sibsp         466.0000
parch         340.0000
fare        28693.9493
dtype: float64

In [104]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [105]:
titanic.fare.cumsum(axis = 0)

0          7.2500
1         78.5333
2         86.4583
3        139.5583
4        147.6083
          ...
886    28602.7493
887    28632.7493
888    28656.1993
889    28686.1993
890    28693.9493
Name: fare, Length: 891, dtype: float64

In [106]:
#titanic.corr() # old

In [107]:
titanic.corr(numeric_only=True) # new

          survived    pclass       age     sibsp     parch      fare
survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
sibsp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [108]:
titanic.survived.corr(titanic.pclass)

np.float64(-0.3384810359610148)