# Appendix 3: Python Libraries Crash Course

## Part 4: Pandas Intermediate 1

### First Steps with Pandas Series

In [144]:
import pandas as pd

In [145]:
titanic = pd.read_csv("titanic.csv")

In [146]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [147]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [148]:
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [149]:
type(titanic["age"])

pandas.core.series.Series

In [150]:
titanic["age"].equals(titanic.age)

True

In [151]:
age = titanic["age"]

In [152]:
age.head(2)

0    22.0
1    38.0
Name: age, dtype: float64

In [153]:
age.tail()

886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, dtype: float64

In [154]:
age.dtype

dtype('float64')

In [155]:
age.shape

(891,)

In [156]:
len(age)

891

In [157]:
age.index

RangeIndex(start=0, stop=891, step=1)

In [158]:
age.info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: age
Non-Null Count  Dtype
--------------  -----
714 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB

In [159]:
age.to_frame().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     714 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB

###  Analyzing Numerical Series

In [160]:
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [161]:
age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [162]:
age.count()

np.int64(714)

In [163]:
age.size

891

In [164]:
len(age)

891

In [165]:
age.sum(skipna = False)

np.float64(nan)

In [166]:
sum(age)

nan

In [167]:
age.mean()

np.float64(29.69911764705882)

In [168]:
age.median()

np.float64(28.0)

In [169]:
age.std()

np.float64(14.526497332334042)

In [170]:
age.min()

np.float64(0.42)

In [171]:
age.max()

np.float64(80.0)

In [172]:
age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [173]:
len(age.unique())

89

In [174]:
age.nunique(dropna = False)

89

In [175]:
age.value_counts()

age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [176]:
age.value_counts(sort = True)

age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [177]:
age.value_counts(sort = False)

age
22.00    27
38.00    11
26.00    18
35.00    18
54.00     8
         ..
0.67      1
30.50     2
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [178]:
age.value_counts(dropna = True)

age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [179]:
age.value_counts(dropna = False)

age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [180]:
age.value_counts(ascending = False)

age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [181]:
age.value_counts(ascending = True)

age
66.0     1
12.0     1
70.5     1
36.5     1
20.5     1
        ..
28.0    25
30.0    25
18.0    26
22.0    27
24.0    30
Name: count, Length: 88, dtype: int64

In [182]:
age.value_counts(sort = True, dropna = True, ascending = False, normalize = False)

age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [183]:
age.value_counts(sort = True, dropna = True, ascending = False, normalize = True)

age
24.00    0.042017
22.00    0.037815
18.00    0.036415
28.00    0.035014
30.00    0.035014
           ...
24.50    0.001401
0.67     0.001401
0.42     0.001401
34.50    0.001401
74.00    0.001401
Name: proportion, Length: 88, dtype: float64

In [184]:
30/age.count()

np.float64(0.04201680672268908)

In [185]:
age.value_counts(sort = True, dropna = False, ascending = False, normalize = True)

age
NaN      0.198653
24.00    0.033670
22.00    0.030303
18.00    0.029181
28.00    0.028058
           ...
24.50    0.001122
0.67     0.001122
0.42     0.001122
34.50    0.001122
74.00    0.001122
Name: proportion, Length: 89, dtype: float64

In [186]:
30/age.size

0.03367003367003367

In [187]:
age.value_counts(sort = True, dropna = True, ascending= False, normalize = False, bins = 5)

(16.336, 32.252]    346
(32.252, 48.168]    188
(0.339, 16.336]     100
(48.168, 64.084]     69
(64.084, 80.0]       11
Name: count, dtype: int64

In [188]:
age.value_counts(sort = True, dropna = True, ascending= False, normalize = True, bins = 10)

(16.336, 24.294]    0.198653
(24.294, 32.252]    0.189675
(32.252, 40.21]     0.132435
(40.21, 48.168]     0.078563
(0.339, 8.378]      0.060606
(8.378, 16.336]     0.051627
(48.168, 56.126]    0.050505
(56.126, 64.084]    0.026936
(64.084, 72.042]    0.010101
(72.042, 80.0]      0.002245
Name: proportion, dtype: float64

### Analyzing non-numerical Series

In [189]:
import pandas as pd

In [190]:
summer = pd.read_csv("summer.csv")

In [191]:
summer.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [192]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31165 entries, 0 to 31164
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Athlete     31165 non-null  object
 5   Country     31161 non-null  object
 6   Gender      31165 non-null  object
 7   Event       31165 non-null  object
 8   Medal       31165 non-null  object
dtypes: int64(1), object(8)
memory usage: 2.1+ MB

In [193]:
athlete = summer["Athlete"]

In [194]:
athlete.head()

0         HAJOS, Alfred
1      HERSCHMANN, Otto
2     DRIVAS, Dimitrios
3    MALOKINIS, Ioannis
4    CHASAPIS, Spiridon
Name: Athlete, dtype: object

In [195]:
athlete.tail(5)

31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, dtype: object

In [196]:
type(athlete)

pandas.core.series.Series

In [197]:
athlete.dtype

dtype('O')

In [198]:
athlete.shape

(31165,)

In [199]:
athlete.describe()

count               31165
unique              22762
top       PHELPS, Michael
freq                   22
Name: Athlete, dtype: object

In [200]:
athlete.size

31165

In [201]:
athlete.count()

np.int64(31165)

In [202]:
athlete.min()

'AABYE, Edgar'

In [203]:
athlete.unique()

array(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios', ...,
       'TOTROV, Rustam', 'ALEKSANYAN, Artur', 'LIDBERG, Jimmy'],
      shape=(22762,), dtype=object)

In [204]:
len(athlete.unique())

22762

In [205]:
athlete.nunique(dropna= False)

22762

In [206]:
athlete.value_counts()

Athlete
PHELPS, Michael         22
LATYNINA, Larisa        18
ANDRIANOV, Nikolay      15
ONO, Takashi            13
MANGIAROTTI, Edoardo    13
                        ..
NABI, Heiki              1
LOPEZ NUNEZ, Mijain      1
LERMUSIAUX, Albin        1
GOULDING, Grantley       1
CURTIS, Thomas           1
Name: count, Length: 22762, dtype: int64

In [207]:
athlete.value_counts(sort = True, ascending=True)

Athlete
GOULDING, Grantley       1
CURTIS, Thomas           1
SZOKOLYI, Alajos         1
LANE, Francis            1
PEPANOS, Antonios        1
                        ..
MANGIAROTTI, Edoardo    13
ONO, Takashi            13
ANDRIANOV, Nikolay      15
LATYNINA, Larisa        18
PHELPS, Michael         22
Name: count, Length: 22762, dtype: int64

In [208]:
athlete.value_counts(sort = True, ascending=False, normalize = True).head()

Athlete
PHELPS, Michael         0.000706
LATYNINA, Larisa        0.000578
ANDRIANOV, Nikolay      0.000481
ONO, Takashi            0.000417
MANGIAROTTI, Edoardo    0.000417
Name: proportion, dtype: float64

### The copy() method

In [209]:
import pandas as pd

In [210]:
titanic = pd.read_csv("titanic.csv")

In [211]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [212]:
age = titanic.age.copy()

In [213]:
age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [214]:
age.iloc[2] = 29

In [215]:
age.head()

0    22.0
1    38.0
2    29.0
3    35.0
4    35.0
Name: age, dtype: float64

In [216]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

### Sorting and introduction to the  inplace-parameter

In [217]:
import pandas as pd

In [218]:
dic = {1:10, 3:25, 2:6, 4:36, 5:2, 6:0, 7:None}
dic

{1: 10, 3: 25, 2: 6, 4: 36, 5: 2, 6: 0, 7: None}

In [219]:
sales = pd.Series(dic)
sales

1    10.0
3    25.0
2     6.0
4    36.0
5     2.0
6     0.0
7     NaN
dtype: float64

In [220]:
sales.sort_index()

1    10.0
2     6.0
3    25.0
4    36.0
5     2.0
6     0.0
7     NaN
dtype: float64

In [221]:
sales.sort_index(ascending = True, inplace= True)

In [222]:
sales

1    10.0
2     6.0
3    25.0
4    36.0
5     2.0
6     0.0
7     NaN
dtype: float64

In [223]:
sales.sort_values(inplace=False)

6     0.0
5     2.0
2     6.0
1    10.0
3    25.0
4    36.0
7     NaN
dtype: float64

In [224]:
sales.sort_values(ascending=False, na_position="last", inplace= True)

In [225]:
sales

4    36.0
3    25.0
1    10.0
2     6.0
5     2.0
6     0.0
7     NaN
dtype: float64

In [226]:
dic = {"Mon":10, "Tue":25, "Wed":6, "Thu": 36, "Fri": 2}
dic

{'Mon': 10, 'Tue': 25, 'Wed': 6, 'Thu': 36, 'Fri': 2}

In [227]:
sales = pd.Series(dic)

In [228]:
sales

Mon    10
Tue    25
Wed     6
Thu    36
Fri     2
dtype: int64

In [229]:
sales.sort_index(ascending=False)

Wed     6
Tue    25
Thu    36
Mon    10
Fri     2
dtype: int64

### First Steps with Pandas Index Objects

In [230]:
import pandas as pd

In [231]:
summer = pd.read_csv("summer.csv", index_col="Athlete")

In [232]:
summer.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [233]:
summer.tail()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [234]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Country     31161 non-null  object
 5   Gender      31165 non-null  object
 6   Event       31165 non-null  object
 7   Medal       31165 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [235]:
summer.index

Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
       'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
       'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
       'NEUMANN, Paul',
       ...
       'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
       'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
       'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
       'LIDBERG, Jimmy'],
      dtype='object', name='Athlete', length=31165)

In [236]:
type(summer.index)

pandas.core.indexes.base.Index

In [237]:
summer.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event',
       'Medal'],
      dtype='object')

In [238]:
type(summer.columns)

pandas.core.indexes.base.Index

In [239]:
summer.axes

[Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
        'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
        'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
        'NEUMANN, Paul',
        ...
        'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
        'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
        'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
        'LIDBERG, Jimmy'],
       dtype='object', name='Athlete', length=31165),
 Index(['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event',
        'Medal'],
       dtype='object')]

In [240]:
summer.columns[:3]

Index(['Year', 'City', 'Sport'], dtype='object')

In [241]:
summer.index[0]

'HAJOS, Alfred'

In [242]:
summer.index[-1]

'LIDBERG, Jimmy'

In [243]:
summer.index[100:102]

Index(['FLATOW, Alfred', 'FLATOW, Gustav Felix'], dtype='object', name='Athlete')

In [244]:
summer.columns.tolist()

['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event', 'Medal']

In [245]:
summer.index.is_unique

False

In [246]:
summer.index.get_loc("DRIVAS, Dimitrios")

2

### Changing Row Index Labels

In [247]:
import pandas as pd

In [248]:
summer = pd.read_csv("summer.csv", index_col="Athlete")

In [249]:
summer.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [250]:
summer.index

Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
       'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
       'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
       'NEUMANN, Paul',
       ...
       'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
       'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
       'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
       'LIDBERG, Jimmy'],
      dtype='object', name='Athlete', length=31165)

In [251]:
summer.reset_index(drop = False, inplace=True)

In [252]:
summer.head()

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
0,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
2,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
3,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
4,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [253]:
summer.set_index("Year", drop = True, inplace = True)

In [254]:
summer.head()

,Athlete,City,Sport,Discipline,Country,Gender,Event,Medal
Year,,,,,,,,
1896,"HAJOS, Alfred",Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1896,"HERSCHMANN, Otto",Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
1896,"DRIVAS, Dimitrios",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
1896,"MALOKINIS, Ioannis",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
1896,"CHASAPIS, Spiridon",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [255]:
summer.index.is_unique

False

In [288]:
summer.index[0] = 1894

TypeError: Index does not support mutable operations

In [289]:
summer.index = "Before 2016"

TypeError: Index(...) must be called with a collection of some kind, 'Before 2016' was passed

In [287]:
summer.index.size

31165

In [290]:
new_index = [f'Medal_No{i}' for i in range(1,summer.index.size+1)]
new_index

['Medal_No1',
 'Medal_No2',
 'Medal_No3',
 'Medal_No4',
 'Medal_No5',
 'Medal_No6',
 'Medal_No7',
 'Medal_No8',
 'Medal_No9',
 'Medal_No10',
 'Medal_No11',
 'Medal_No12',
 'Medal_No13',
 'Medal_No14',
 'Medal_No15',
 'Medal_No16',
 'Medal_No17',
 'Medal_No18',
 'Medal_No19',
 'Medal_No20',
 'Medal_No21',
 'Medal_No22',
 'Medal_No23',
 'Medal_No24',
 'Medal_No25',
 'Medal_No26',
 'Medal_No27',
 'Medal_No28',
 'Medal_No29',
 'Medal_No30',
 'Medal_No31',
 'Medal_No32',
 'Medal_No33',
 'Medal_No34',
 'Medal_No35',
 'Medal_No36',
 'Medal_No37',
 'Medal_No38',
 'Medal_No39',
 'Medal_No40',
 'Medal_No41',
 'Medal_No42',
 'Medal_No43',
 'Medal_No44',
 'Medal_No45',
 'Medal_No46',
 'Medal_No47',
 'Medal_No48',
 'Medal_No49',
 'Medal_No50',
 'Medal_No51',
 'Medal_No52',
 'Medal_No53',
 'Medal_No54',
 'Medal_No55',
 'Medal_No56',
 'Medal_No57',
 'Medal_No58',
 'Medal_No59',
 'Medal_No60',
 'Medal_No61',
 'Medal_No62',
 'Medal_No63',
 'Medal_No64',
 'Medal_No65',
 'Medal_No66',
 'Medal_No67',
 'Medal_No68',
 'Medal_No69',
 'Medal_No70',
 'Medal_No71',
 'Medal_No72',
 'Medal_No73',
 'Medal_No74',
 'Medal_No75',
 'Medal_No76',
 'Medal_No77',
 'Medal_No78',
 'Medal_No79',
 'Medal_No80',
 'Medal_No81',
 'Medal_No82',
 'Medal_No83',
 'Medal_No84',
 'Medal_No85',
 'Medal_No86',
 'Medal_No87',
 'Medal_No88',
 'Medal_No89',
 'Medal_No90',
 'Medal_No91',
 'Medal_No92',
 'Medal_No93',
 'Medal_No94',
 'Medal_No95',
 'Medal_No96',
 'Medal_No97',
 'Medal_No98',
 'Medal_No99',
 'Medal_No100',
 'Medal_No101',
 'Medal_No102',
 'Medal_No103',
 'Medal_No104',
 'Medal_No105',
 'Medal_No106',
 'Medal_No107',
 'Medal_No108',
 'Medal_No109',
 'Medal_No110',
 'Medal_No111',
 'Medal_No112',
 'Medal_No113',
 'Medal_No114',
 'Medal_No115',
 'Medal_No116',
 'Medal_No117',
 'Medal_No118',
 'Medal_No119',
 'Medal_No120',
 'Medal_No121',
 'Medal_No122',
 'Medal_No123',
 'Medal_No124',
 'Medal_No125',
 'Medal_No126',
 'Medal_No127',
 'Medal_No128',
 'Medal_No129',
 'Medal_No130',
 'Medal_No131',
 'Medal_No132',
 'Medal_No133',
 'Medal_No134',
 'Medal_No135',
 'Medal_No136',
 'Medal_No137',
 'Medal_No138',
 'Medal_No139',
 'Medal_No140',
 'Medal_No141',
 'Medal_No142',
 'Medal_No143',
 'Medal_No144',
 'Medal_No145',
 'Medal_No146',
 'Medal_No147',
 'Medal_No148',
 'Medal_No149',
 'Medal_No150',
 'Medal_No151',
 'Medal_No152',
 'Medal_No153',
 'Medal_No154',
 'Medal_No155',
 'Medal_No156',
 'Medal_No157',
 'Medal_No158',
 'Medal_No159',
 'Medal_No160',
 'Medal_No161',
 'Medal_No162',
 'Medal_No163',
 'Medal_No164',
 'Medal_No165',
 'Medal_No166',
 'Medal_No167',
 'Medal_No168',
 'Medal_No169',
 'Medal_No170',
 'Medal_No171',
 'Medal_No172',
 'Medal_No173',
 'Medal_No174',
 'Medal_No175',
 'Medal_No176',
 'Medal_No177',
 'Medal_No178',
 'Medal_No179',
 'Medal_No180',
 'Medal_No181',
 'Medal_No182',
 'Medal_No183',
 'Medal_No184',
 'Medal_No185',
 'Medal_No186',
 'Medal_No187',
 'Medal_No188',
 'Medal_No189',
 'Medal_No190',
 'Medal_No191',
 'Medal_No192',
 'Medal_No193',
 'Medal_No194',
 'Medal_No195',
 'Medal_No196',
 'Medal_No197',
 'Medal_No198',
 'Medal_No199',
 'Medal_No200',
 'Medal_No201',
 'Medal_No202',
 'Medal_No203',
 'Medal_No204',
 'Medal_No205',
 'Medal_No206',
 'Medal_No207',
 'Medal_No208',
 'Medal_No209',
 'Medal_No210',
 'Medal_No211',
 'Medal_No212',
 'Medal_No213',
 'Medal_No214',
 'Medal_No215',
 'Medal_No216',
 'Medal_No217',
 'Medal_No218',
 'Medal_No219',
 'Medal_No220',
 'Medal_No221',
 'Medal_No222',
 'Medal_No223',
 'Medal_No224',
 'Medal_No225',
 'Medal_No226',
 'Medal_No227',
 'Medal_No228',
 'Medal_No229',
 'Medal_No230',
 'Medal_No231',
 'Medal_No232',
 'Medal_No233',
 'Medal_No234',
 'Medal_No235',
 'Medal_No236',
 'Medal_No237',
 'Medal_No238',
 'Medal_No239',
 'Medal_No240',
 'Medal_No241',
 'Medal_No242',
 'Medal_No243',
 'Medal_No244',
 'Medal_No245',
 'Medal_No246',
 'Medal_No247',
 'Medal_No248',
 'Medal_No249',
 'Medal_No250',
 'Medal_No251',
 'Medal_No252',
 'Medal_No253',
 'Medal_No254',
 'Medal_No255',
 'Medal_No256',
 'Medal_No257',
 'Medal_No258',
 'Medal_No259',
 'Medal_No260',
 'Medal_No261',
 'Medal_No262',
 'Medal_No263',
 'Medal_No264',
 'Medal_No265',
 'Medal_No266',
 'Medal_No267',
 'Medal_No268',
 'Medal_No269',
 'Medal_No270',
 'Medal_No271',
 'Medal_No272',
 'Medal_No273',
 'Medal_No274',
 'Medal_No275',
 'Medal_No276',
 'Medal_No277',
 'Medal_No278',
 'Medal_No279',
 'Medal_No280',
 'Medal_No281',
 'Medal_No282',
 'Medal_No283',
 'Medal_No284',
 'Medal_No285',
 'Medal_No286',
 'Medal_No287',
 'Medal_No288',
 'Medal_No289',
 'Medal_No290',
 'Medal_No291',
 'Medal_No292',
 'Medal_No293',
 'Medal_No294',
 'Medal_No295',
 'Medal_No296',
 'Medal_No297',
 'Medal_No298',
 'Medal_No299',
 'Medal_No300',
 'Medal_No301',
 'Medal_No302',
 'Medal_No303',
 'Medal_No304',
 'Medal_No305',
 'Medal_No306',
 'Medal_No307',
 'Medal_No308',
 'Medal_No309',
 'Medal_No310',
 'Medal_No311',
 'Medal_No312',
 'Medal_No313',
 'Medal_No314',
 'Medal_No315',
 'Medal_No316',
 'Medal_No317',
 'Medal_No318',
 'Medal_No319',
 'Medal_No320',
 'Medal_No321',
 'Medal_No322',
 'Medal_No323',
 'Medal_No324',
 'Medal_No325',
 'Medal_No326',
 'Medal_No327',
 'Medal_No328',
 'Medal_No329',
 'Medal_No330',
 'Medal_No331',
 'Medal_No332',
 'Medal_No333',
 'Medal_No334',
 'Medal_No335',
 'Medal_No336',
 'Medal_No337',
 'Medal_No338',
 'Medal_No339',
 'Medal_No340',
 'Medal_No341',
 'Medal_No342',
 'Medal_No343',
 'Medal_No344',
 'Medal_No345',
 'Medal_No346',
 'Medal_No347',
 'Medal_No348',
 'Medal_No349',
 'Medal_No350',
 'Medal_No351',
 'Medal_No352',
 'Medal_No353',
 'Medal_No354',
 'Medal_No355',
 'Medal_No356',
 'Medal_No357',
 'Medal_No358',
 'Medal_No359',
 'Medal_No360',
 'Medal_No361',
 'Medal_No362',
 'Medal_No363',
 'Medal_No364',
 'Medal_No365',
 'Medal_No366',
 'Medal_No367',
 'Medal_No368',
 'Medal_No369',
 'Medal_No370',
 'Medal_No371',
 'Medal_No372',
 'Medal_No373',
 'Medal_No374',
 'Medal_No375',
 'Medal_No376',
 'Medal_No377',
 'Medal_No378',
 'Medal_No379',
 'Medal_No380',
 'Medal_No381',
 'Medal_No382',
 'Medal_No383',
 'Medal_No384',
 'Medal_No385',
 'Medal_No386',
 'Medal_No387',
 'Medal_No388',
 'Medal_No389',
 'Medal_No390',
 'Medal_No391',
 'Medal_No392',
 'Medal_No393',
 'Medal_No394',
 'Medal_No395',
 'Medal_No396',
 'Medal_No397',
 'Medal_No398',
 'Medal_No399',
 'Medal_No400',
 'Medal_No401',
 'Medal_No402',
 'Medal_No403',
 'Medal_No404',
 'Medal_No405',
 'Medal_No406',
 'Medal_No407',
 'Medal_No408',
 'Medal_No409',
 'Medal_No410',
 'Medal_No411',
 'Medal_No412',
 'Medal_No413',
 'Medal_No414',
 'Medal_No415',
 'Medal_No416',
 'Medal_No417',
 'Medal_No418',
 'Medal_No419',
 'Medal_No420',
 'Medal_No421',
 'Medal_No422',
 'Medal_No423',
 'Medal_No424',
 'Medal_No425',
 'Medal_No426',
 'Medal_No427',
 'Medal_No428',
 'Medal_No429',
 'Medal_No430',
 'Medal_No431',
 'Medal_No432',
 'Medal_No433',
 'Medal_No434',
 'Medal_No435',
 'Medal_No436',
 'Medal_No437',
 'Medal_No438',
 'Medal_No439',
 'Medal_No440',
 'Medal_No441',
 'Medal_No442',
 'Medal_No443',
 'Medal_No444',
 'Medal_No445',
 'Medal_No446',
 'Medal_No447',
 'Medal_No448',
 'Medal_No449',
 'Medal_No450',
 'Medal_No451',
 'Medal_No452',
 'Medal_No453',
 'Medal_No454',
 'Medal_No455',
 'Medal_No456',
 'Medal_No457',
 'Medal_No458',
 'Medal_No459',
 'Medal_No460',
 'Medal_No461',
 'Medal_No462',
 'Medal_No463',
 'Medal_No464',
 'Medal_No465',
 'Medal_No466',
 'Medal_No467',
 'Medal_No468',
 'Medal_No469',
 'Medal_No470',
 'Medal_No471',
 'Medal_No472',
 'Medal_No473',
 'Medal_No474',
 'Medal_No475',
 'Medal_No476',
 'Medal_No477',
 'Medal_No478',
 'Medal_No479',
 'Medal_No480',
 'Medal_No481',
 'Medal_No482',
 'Medal_No483',
 'Medal_No484',
 'Medal_No485',
 'Medal_No486',
 'Medal_No487',
 'Medal_No488',
 'Medal_No489',
 'Medal_No490',
 'Medal_No491',
 'Medal_No492',
 'Medal_No493',
 'Medal_No494',
 'Medal_No495',
 'Medal_No496',
 'Medal_No497',
 'Medal_No498',
 'Medal_No499',
 'Medal_No500',
 'Medal_No501',
 'Medal_No502',
 'Medal_No503',
 'Medal_No504',
 'Medal_No505',
 'Medal_No506',
 'Medal_No507',
 'Medal_No508',
 'Medal_No509',
 'Medal_No510',
 'Medal_No511',
 'Medal_No512',
 'Medal_No513',
 'Medal_No514',
 'Medal_No515',
 'Medal_No516',
 'Medal_No517',
 'Medal_No518',
 'Medal_No519',
 'Medal_No520',
 'Medal_No521',
 'Medal_No522',
 'Medal_No523',
 'Medal_No524',
 'Medal_No525',
 'Medal_No526',
 'Medal_No527',
 'Medal_No528',
 'Medal_No529',
 'Medal_No530',
 'Medal_No531',
 'Medal_No532',
 'Medal_No533',
 'Medal_No534',
 'Medal_No535',
 'Medal_No536',
 'Medal_No537',
 'Medal_No538',
 'Medal_No539',
 'Medal_No540',
 'Medal_No541',
 'Medal_No542',
 'Medal_No543',
 'Medal_No544',
 'Medal_No545',
 'Medal_No546',
 'Medal_No547',
 'Medal_No548',
 'Medal_No549',
 'Medal_No550',
 'Medal_No551',
 'Medal_No552',
 'Medal_No553',
 'Medal_No554',
 'Medal_No555',
 'Medal_No556',
 'Medal_No557',
 'Medal_No558',
 'Medal_No559',
 'Medal_No560',
 'Medal_No561',
 'Medal_No562',
 'Medal_No563',
 'Medal_No564',
 'Medal_No565',
 'Medal_No566',
 'Medal_No567',
 'Medal_No568',
 'Medal_No569',
 'Medal_No570',
 'Medal_No571',
 'Medal_No572',
 'Medal_No573',
 'Medal_No574',
 'Medal_No575',
 'Medal_No576',
 'Medal_No577',
 'Medal_No578',
 'Medal_No579',
 'Medal_No580',
 'Medal_No581',
 'Medal_No582',
 'Medal_No583',
 'Medal_No584',
 'Medal_No585',
 'Medal_No586',
 'Medal_No587',
 'Medal_No588',
 'Medal_No589',
 'Medal_No590',
 'Medal_No591',
 'Medal_No592',
 'Medal_No593',
 'Medal_No594',
 'Medal_No595',
 'Medal_No596',
 'Medal_No597',
 'Medal_No598',
 'Medal_No599',
 'Medal_No600',
 'Medal_No601',
 'Medal_No602',
 'Medal_No603',
 'Medal_No604',
 'Medal_No605',
 'Medal_No606',
 'Medal_No607',
 'Medal_No608',
 'Medal_No609',
 'Medal_No610',
 'Medal_No611',
 'Medal_No612',
 'Medal_No613',
 'Medal_No614',
 'Medal_No615',
 'Medal_No616',
 'Medal_No617',
 'Medal_No618',
 'Medal_No619',
 'Medal_No620',
 'Medal_No621',
 'Medal_No622',
 'Medal_No623',
 'Medal_No624',
 'Medal_No625',
 'Medal_No626',
 'Medal_No627',
 'Medal_No628',
 'Medal_No629',
 'Medal_No630',
 'Medal_No631',
 'Medal_No632',
 'Medal_No633',
 'Medal_No634',
 'Medal_No635',
 'Medal_No636',
 'Medal_No637',
 'Medal_No638',
 'Medal_No639',
 'Medal_No640',
 'Medal_No641',
 'Medal_No642',
 'Medal_No643',
 'Medal_No644',
 'Medal_No645',
 'Medal_No646',
 'Medal_No647',
 'Medal_No648',
 'Medal_No649',
 'Medal_No650',
 'Medal_No651',
 'Medal_No652',
 'Medal_No653',
 'Medal_No654',
 'Medal_No655',
 'Medal_No656',
 'Medal_No657',
 'Medal_No658',
 'Medal_No659',
 'Medal_No660',
 'Medal_No661',
 'Medal_No662',
 'Medal_No663',
 'Medal_No664',
 'Medal_No665',
 'Medal_No666',
 'Medal_No667',
 'Medal_No668',
 'Medal_No669',
 'Medal_No670',
 'Medal_No671',
 'Medal_No672',
 'Medal_No673',
 'Medal_No674',
 'Medal_No675',
 'Medal_No676',
 'Medal_No677',
 'Medal_No678',
 'Medal_No679',
 'Medal_No680',
 'Medal_No681',
 'Medal_No682',
 'Medal_No683',
 'Medal_No684',
 'Medal_No685',
 'Medal_No686',
 'Medal_No687',
 'Medal_No688',
 'Medal_No689',
 'Medal_No690',
 'Medal_No691',
 'Medal_No692',
 'Medal_No693',
 'Medal_No694',
 'Medal_No695',
 'Medal_No696',
 'Medal_No697',
 'Medal_No698',
 'Medal_No699',
 'Medal_No700',
 'Medal_No701',
 'Medal_No702',
 'Medal_No703',
 'Medal_No704',
 'Medal_No705',
 'Medal_No706',
 'Medal_No707',
 'Medal_No708',
 'Medal_No709',
 'Medal_No710',
 'Medal_No711',
 'Medal_No712',
 'Medal_No713',
 'Medal_No714',
 'Medal_No715',
 'Medal_No716',
 'Medal_No717',
 'Medal_No718',
 'Medal_No719',
 'Medal_No720',
 'Medal_No721',
 'Medal_No722',
 'Medal_No723',
 'Medal_No724',
 'Medal_No725',
 'Medal_No726',
 'Medal_No727',
 'Medal_No728',
 'Medal_No729',
 'Medal_No730',
 'Medal_No731',
 'Medal_No732',
 'Medal_No733',
 'Medal_No734',
 'Medal_No735',
 'Medal_No736',
 'Medal_No737',
 'Medal_No738',
 'Medal_No739',
 'Medal_No740',
 'Medal_No741',
 'Medal_No742',
 'Medal_No743',
 'Medal_No744',
 'Medal_No745',
 'Medal_No746',
 'Medal_No747',
 'Medal_No748',
 'Medal_No749',
 'Medal_No750',
 'Medal_No751',
 'Medal_No752',
 'Medal_No753',
 'Medal_No754',
 'Medal_No755',
 'Medal_No756',
 'Medal_No757',
 'Medal_No758',
 'Medal_No759',
 'Medal_No760',
 'Medal_No761',
 'Medal_No762',
 'Medal_No763',
 'Medal_No764',
 'Medal_No765',
 'Medal_No766',
 'Medal_No767',
 'Medal_No768',
 'Medal_No769',
 'Medal_No770',
 'Medal_No771',
 'Medal_No772',
 'Medal_No773',
 'Medal_No774',
 'Medal_No775',
 'Medal_No776',
 'Medal_No777',
 'Medal_No778',
 'Medal_No779',
 'Medal_No780',
 'Medal_No781',
 'Medal_No782',
 'Medal_No783',
 'Medal_No784',
 'Medal_No785',
 'Medal_No786',
 'Medal_No787',
 'Medal_No788',
 'Medal_No789',
 'Medal_No790',
 'Medal_No791',
 'Medal_No792',
 'Medal_No793',
 'Medal_No794',
 'Medal_No795',
 'Medal_No796',
 'Medal_No797',
 'Medal_No798',
 'Medal_No799',
 'Medal_No800',
 'Medal_No801',
 'Medal_No802',
 'Medal_No803',
 'Medal_No804',
 'Medal_No805',
 'Medal_No806',
 'Medal_No807',
 'Medal_No808',
 'Medal_No809',
 'Medal_No810',
 'Medal_No811',
 'Medal_No812',
 'Medal_No813',
 'Medal_No814',
 'Medal_No815',
 'Medal_No816',
 'Medal_No817',
 'Medal_No818',
 'Medal_No819',
 'Medal_No820',
 'Medal_No821',
 'Medal_No822',
 'Medal_No823',
 'Medal_No824',
 'Medal_No825',
 'Medal_No826',
 'Medal_No827',
 'Medal_No828',
 'Medal_No829',
 'Medal_No830',
 'Medal_No831',
 'Medal_No832',
 'Medal_No833',
 'Medal_No834',
 'Medal_No835',
 'Medal_No836',
 'Medal_No837',
 'Medal_No838',
 'Medal_No839',
 'Medal_No840',
 'Medal_No841',
 'Medal_No842',
 'Medal_No843',
 'Medal_No844',
 'Medal_No845',
 'Medal_No846',
 'Medal_No847',
 'Medal_No848',
 'Medal_No849',
 'Medal_No850',
 'Medal_No851',
 'Medal_No852',
 'Medal_No853',
 'Medal_No854',
 'Medal_No855',
 'Medal_No856',
 'Medal_No857',
 'Medal_No858',
 'Medal_No859',
 'Medal_No860',
 'Medal_No861',
 'Medal_No862',
 'Medal_No863',
 'Medal_No864',
 'Medal_No865',
 'Medal_No866',
 'Medal_No867',
 'Medal_No868',
 'Medal_No869',
 'Medal_No870',
 'Medal_No871',
 'Medal_No872',
 'Medal_No873',
 'Medal_No874',
 'Medal_No875',
 'Medal_No876',
 'Medal_No877',
 'Medal_No878',
 'Medal_No879',
 'Medal_No880',
 'Medal_No881',
 'Medal_No882',
 'Medal_No883',
 'Medal_No884',
 'Medal_No885',
 'Medal_No886',
 'Medal_No887',
 'Medal_No888',
 'Medal_No889',
 'Medal_No890',
 'Medal_No891',
 'Medal_No892',
 'Medal_No893',
 'Medal_No894',
 'Medal_No895',
 'Medal_No896',
 'Medal_No897',
 'Medal_No898',
 'Medal_No899',
 'Medal_No900',
 'Medal_No901',
 'Medal_No902',
 'Medal_No903',
 'Medal_No904',
 'Medal_No905',
 'Medal_No906',
 'Medal_No907',
 'Medal_No908',
 'Medal_No909',
 'Medal_No910',
 'Medal_No911',
 'Medal_No912',
 'Medal_No913',
 'Medal_No914',
 'Medal_No915',
 'Medal_No916',
 'Medal_No917',
 'Medal_No918',
 'Medal_No919',
 'Medal_No920',
 'Medal_No921',
 'Medal_No922',
 'Medal_No923',
 'Medal_No924',
 'Medal_No925',
 'Medal_No926',
 'Medal_No927',
 'Medal_No928',
 'Medal_No929',
 'Medal_No930',
 'Medal_No931',
 'Medal_No932',
 'Medal_No933',
 'Medal_No934',
 'Medal_No935',
 'Medal_No936',
 'Medal_No937',
 'Medal_No938',
 'Medal_No939',
 'Medal_No940',
 'Medal_No941',
 'Medal_No942',
 'Medal_No943',
 'Medal_No944',
 'Medal_No945',
 'Medal_No946',
 'Medal_No947',
 'Medal_No948',
 'Medal_No949',
 'Medal_No950',
 'Medal_No951',
 'Medal_No952',
 'Medal_No953',
 'Medal_No954',
 'Medal_No955',
 'Medal_No956',
 'Medal_No957',
 'Medal_No958',
 'Medal_No959',
 'Medal_No960',
 'Medal_No961',
 'Medal_No962',
 'Medal_No963',
 'Medal_No964',
 'Medal_No965',
 'Medal_No966',
 'Medal_No967',
 'Medal_No968',
 'Medal_No969',
 'Medal_No970',
 'Medal_No971',
 'Medal_No972',
 'Medal_No973',
 'Medal_No974',
 'Medal_No975',
 'Medal_No976',
 'Medal_No977',
 'Medal_No978',
 'Medal_No979',
 'Medal_No980',
 'Medal_No981',
 'Medal_No982',
 'Medal_No983',
 'Medal_No984',
 'Medal_No985',
 'Medal_No986',
 'Medal_No987',
 'Medal_No988',
 'Medal_No989',
 'Medal_No990',
 'Medal_No991',
 'Medal_No992',
 'Medal_No993',
 'Medal_No994',
 'Medal_No995',
 'Medal_No996',
 'Medal_No997',
 'Medal_No998',
 'Medal_No999',
 'Medal_No1000',
 ...]

In [260]:
summer.index = new_index

In [261]:
summer.head()

,Athlete,City,Sport,Discipline,Country,Gender,Event,Medal
Medal_No1,"HAJOS, Alfred",Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal_No2,"HERSCHMANN, Otto",Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal_No3,"DRIVAS, Dimitrios",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal_No4,"MALOKINIS, Ioannis",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal_No5,"CHASAPIS, Spiridon",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [262]:
summer.tail()

,Athlete,City,Sport,Discipline,Country,Gender,Event,Medal
Medal_No31161,"JANIKOWSKI, Damian",London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal_No31162,"REZAEI, Ghasem Gholamreza",London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal_No31163,"TOTROV, Rustam",London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal_No31164,"ALEKSANYAN, Artur",London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal_No31165,"LIDBERG, Jimmy",London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [291]:
summer.index.is_unique

False

In [264]:
summer.index.name = "Medal_No"

In [265]:
summer.reset_index()

,Medal_No,Athlete,City,Sport,Discipline,Country,Gender,Event,Medal
0,Medal_No1,"HAJOS, Alfred",Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1,Medal_No2,"HERSCHMANN, Otto",Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
2,Medal_No3,"DRIVAS, Dimitrios",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
3,Medal_No4,"MALOKINIS, Ioannis",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
4,Medal_No5,"CHASAPIS, Spiridon",Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,Medal_No31161,"JANIKOWSKI, Damian",London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
31161,Medal_No31162,"REZAEI, Ghasem Gholamreza",London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
31162,Medal_No31163,"TOTROV, Rustam",London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
31163,Medal_No31164,"ALEKSANYAN, Artur",London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
31164,Medal_No31165,"LIDBERG, Jimmy",London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

### Changing Column Labels

In [266]:
import pandas as pd

In [267]:
titanic = pd.read_csv("titanic.csv")

In [268]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [269]:
titanic.tail()

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [270]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [271]:
titanic.columns[0]

'survived'

In [272]:
#titanic.columns[0] = "Alive"

In [273]:
titanic.columns = ["Alive", "Class", "Sex", "Age", "SibSp", "ParChi", "Fare", "Emb", "Deck"]

In [274]:
titanic.head()

   Alive  Class     Sex   Age  SibSp  ParChi     Fare Emb Deck
0      0      3    male  22.0      1       0   7.2500   S  NaN
1      1      1  female  38.0      1       0  71.2833   C    C
2      1      3  female  26.0      0       0   7.9250   S  NaN
3      1      1  female  35.0      1       0  53.1000   S    C
4      0      3    male  35.0      0       0   8.0500   S  NaN

In [293]:
titanic.columns.name

'Pass_Charact'

In [294]:
titanic.columns.name = "Pass_Charact"

In [295]:
titanic.head()

Pass_Charact  Alive  Class     Sex   Age  SibSp  ParChi     Fare Emb Deck
Passenger_no
0                 0      3    male  22.0      1       0   7.2500   S  NaN
1                 1      1  female  38.0      1       0  71.2833   C    C
2                 1      3  female  26.0      0       0   7.9250   S  NaN
3                 1      1  female  35.0      1       0  53.1000   S    C
4                 0      3    male  35.0      0       0   8.0500   S  NaN

In [296]:
titanic.index.name = "Passenger_no"

In [299]:
titanic.head()

Pass_Charact  Alive  Class     Sex   Age  SibSp  ParChi     Fare Emb Deck
Passenger_no
0                 0      3    male  22.0      1       0   7.2500   S  NaN
1                 1      1  female  38.0      1       0  71.2833   C    C
2                 1      3  female  26.0      0       0   7.9250   S  NaN
3                 1      1  female  35.0      1       0  53.1000   S    C
4                 0      3    male  35.0      0       0   8.0500   S  NaN

### Renaming Index & Column Labels

In [279]:
import pandas as pd

In [280]:
summer= pd.read_csv("summer.csv", index_col = "Athlete")

In [281]:
summer.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [282]:
#summer.index[0] = 'HAYOS, Alfred'

In [283]:
summer.rename({"HAJOS, Alfred":'HAYOS, Alfred'}, axis = "index", inplace= True)

In [284]:
summer.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAYOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [285]:
summer.rename({"Gender":'Sex', "City":"Host_City"}, axis = "columns", inplace=True)

In [286]:
summer.head()

,Year,Host_City,Sport,Discipline,Country,Sex,Event,Medal
Athlete,,,,,,,,
"HAYOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver