In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-v0_8')

In [5]:
plt.style.available

['Solarize_Light2',
 '_classic_test_patch',
 '_mpl-gallery',
 '_mpl-gallery-nogrid',
 'bmh',
 'classic',
 'dark_background',
 'fast',
 'fivethirtyeight',
 'ggplot',
 'grayscale',
 'petroff10',
 'seaborn-v0_8',
 'seaborn-v0_8-bright',
 'seaborn-v0_8-colorblind',
 'seaborn-v0_8-dark',
 'seaborn-v0_8-dark-palette',
 'seaborn-v0_8-darkgrid',
 'seaborn-v0_8-deep',
 'seaborn-v0_8-muted',
 'seaborn-v0_8-notebook',
 'seaborn-v0_8-paper',
 'seaborn-v0_8-pastel',
 'seaborn-v0_8-poster',
 'seaborn-v0_8-talk',
 'seaborn-v0_8-ticks',
 'seaborn-v0_8-white',
 'seaborn-v0_8-whitegrid',
 'tableau-colorblind10']

In [7]:
msft=pd.read_csv(r'C:\Users\bedla\Documents\Ausbildung_Informatik\1_Praktikum\Praktikum_Daten-_und_Prozessanalyse\energy_trading\PyCharm_Notebook\Data\msft.csv', index_col='Date', parse_dates=['Date'])
msft

                 Price   Returns
Date
2014-10-01   38.880157       NaN
2014-10-02   38.761566 -0.003050
2014-10-03   39.041096  0.007212
2014-10-06   39.041096  0.000000
2014-10-07   38.566757 -0.012150
...                ...       ...
2021-05-24  241.744537  0.022882
2021-05-25  242.650665  0.003748
2021-05-26  242.428940 -0.000914
2021-05-27  240.327499 -0.008668
2021-05-28  240.684128  0.001484

[1677 rows x 2 columns]

In [8]:
msft['log_returns']=np.log(msft.Price/msft.Price.shift()) #daily Log Returns
msft

                 Price   Returns  log_returns
Date
2014-10-01   38.880157       NaN          NaN
2014-10-02   38.761566 -0.003050    -0.003055
2014-10-03   39.041096  0.007212     0.007186
2014-10-06   39.041096  0.000000     0.000000
2014-10-07   38.566757 -0.012150    -0.012224
...                ...       ...          ...
2021-05-24  241.744537  0.022882     0.022624
2021-05-25  242.650665  0.003748     0.003741
2021-05-26  242.428940 -0.000914    -0.000914
2021-05-27  240.327499 -0.008668    -0.008706
2021-05-28  240.684128  0.001484     0.001483

[1677 rows x 3 columns]

In [9]:
msft.log_returns.agg(['mean','std'])

mean    0.001088
std     0.017233
Name: log_returns, dtype: float64

In [10]:
ann_mu=msft.log_returns.mean()*252 # annualized mean return
ann_mu

np.float64(0.2741028314472096)

In [11]:
cagr=np.exp(ann_mu)-1 # don´t mix it up with cagr
cagr

np.float64(0.31535005463421073)

In [17]:
ann_std=msft.log_returns.std()*np.sqrt(252) #annualized std or returns (Alternative 1)
ann_std

np.float64(0.2735618746370175)

In [20]:
ann_std=np.sqrt(msft.log_returns.var()*252) #annualized std or returns (Alternative 2)
ann_std

np.float64(0.27356187463701753)