# Portfolio of Assets and Portfolio Returns

In [1]:
import pandas as pd
import numpy  as np

In [2]:
prices=pd.DataFrame(data={'Asset_A':[100,112],'Asset_B':[100,104]})
prices

   Asset_A  Asset_B
0      100      100
1      112      104

In [3]:
prices['Total']=prices.Asset_A+prices.Asset_B
prices

   Asset_A  Asset_B  Total
0      100      100    200
1      112      104    216

In [4]:
returns=prices.pct_change() # simple returns
returns

   Asset_A  Asset_B  Total
0      NaN      NaN    NaN
1     0.12     0.04   0.08

**Portfoliorendite (portfolio return)==Gewichteter Durchschnitt (50%=0.5) einfacher Rendite (weighted average of simple returns)**

In [5]:
0.5*0.12+0.5*0.04

0.08

In [6]:
log_returns=np.log(prices/prices.shift()) # Log returns
log_returns

    Asset_A   Asset_B     Total
0       NaN       NaN       NaN
1  0.113329  0.039221  0.076961

In [7]:
0.5*log_returns.iloc[1,0]+0.5*log_returns.iloc[1,1]

np.float64(0.0762746992301423)

# **Take Home: While Log Return are time-additive, they are not asset-additive.**
(While simple returns are asset-additive, they are not time-additive)